<?php

declare(strict_types=1);
/**
 * MeApi
 * PHP version 7.4
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Resources;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SignWell\Sdk\ApiException;
use SignWell\Sdk\Configuration;
use SignWell\Sdk\HeaderSelector;
use SignWell\Sdk\ObjectSerializer;

/**
 * MeApi Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class MeApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getMe' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getMe
     *
     * Get credentials
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMe'] to see the possible values for this operation
     *
     * @throws \SignWell\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SignWell\Sdk\Models\MeResponse|\SignWell\Sdk\Models\ErrorResponse|\SignWell\Sdk\Models\RateLimitErrorResponse
     */
    public function getMe(string $contentType = self::contentTypes['getMe'][0])
    {
        list($response) = $this->getMeWithHttpInfo($contentType);
        return $response;
    }

    /**
     * Operation getMeWithHttpInfo
     *
     * Get credentials
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMe'] to see the possible values for this operation
     *
     * @throws \SignWell\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SignWell\Sdk\Models\MeResponse|\SignWell\Sdk\Models\ErrorResponse|\SignWell\Sdk\Models\RateLimitErrorResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMeWithHttpInfo(string $contentType = self::contentTypes['getMe'][0])
    {
        $request = $this->getMeRequest($contentType);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        (int) $e->getCode(),
                        $this->sanitizeRequestUri($e->getRequest())
                    ),
                    (int) $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null,
                    $e
                );
            } catch (ConnectException $e) {
                throw new \SignWell\Sdk\Errors\ApiConnectionError(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        (int) $e->getCode(),
                        $this->sanitizeRequestUri($request)
                    ),
                    (int) $e->getCode(),
                    null,
                    null,
                    $e
                );
            }

            $statusCode = $response->getStatusCode();


            switch ($statusCode) {
                case 200:
                    if ('\SignWell\Sdk\Models\MeResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SignWell\Sdk\Models\MeResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw ApiException::fromResponse(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $this->sanitizeRequestUri($request)
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SignWell\Sdk\Models\MeResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 401:
                    if ('\SignWell\Sdk\Models\ErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SignWell\Sdk\Models\ErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw ApiException::fromResponse(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $this->sanitizeRequestUri($request)
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SignWell\Sdk\Models\ErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                case 429:
                    if ('\SignWell\Sdk\Models\RateLimitErrorResponse' === '\SplFileObject') {
                        $content = $response->getBody(); //stream goes to serializer
                    } else {
                        $content = (string) $response->getBody();
                        if ('\SignWell\Sdk\Models\RateLimitErrorResponse' !== 'string') {
                            try {
                                $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                            } catch (\JsonException $exception) {
                                throw ApiException::fromResponse(
                                    sprintf(
                                        'Error JSON decoding server response (%s)',
                                        $this->sanitizeRequestUri($request)
                                    ),
                                    $statusCode,
                                    $response->getHeaders(),
                                    $content
                                );
                            }
                        }
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\SignWell\Sdk\Models\RateLimitErrorResponse', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            if ($statusCode < 200 || $statusCode > 299) {
                throw ApiException::fromResponse(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $this->sanitizeRequestUri($request)
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    (string) $response->getBody()
                );
            }

            $returnType = '\SignWell\Sdk\Models\MeResponse';
            if ($returnType === '\SplFileObject') {
                $content = $response->getBody(); //stream goes to serializer
            } else {
                $content = (string) $response->getBody();
                if ($returnType !== 'string') {
                    try {
                        $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                    } catch (\JsonException $exception) {
                        throw ApiException::fromResponse(
                            sprintf(
                                'Error JSON decoding server response (%s)',
                                $this->sanitizeRequestUri($request)
                            ),
                            $statusCode,
                            $response->getHeaders(),
                            $content
                        );
                    }
                }
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\MeResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 401:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\RateLimitErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMeAsync
     *
     * Get credentials
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMeAsync(string $contentType = self::contentTypes['getMe'][0])
    {
        return $this->getMeAsyncWithHttpInfo($contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMeAsyncWithHttpInfo
     *
     * Get credentials
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMeAsyncWithHttpInfo(string $contentType = self::contentTypes['getMe'][0])
    {
        $returnType = '\SignWell\Sdk\Models\MeResponse';
        $request = $this->getMeRequest($contentType);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function (ResponseInterface $response) use ($request, $returnType) {
                    return $this->deserializeResponse($response, $request, $returnType);
                },
                function ($exception) use ($request) {
                    if ($exception instanceof ConnectException) {
                        throw new \SignWell\Sdk\Errors\ApiConnectionError(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                (int) $exception->getCode(),
                                $this->sanitizeRequestUri($request)
                            ),
                            (int) $exception->getCode(),
                            null,
                            null,
                            $exception
                        );
                    }

                    $response = $exception instanceof RequestException ? $exception->getResponse() : null;
                    if ($response === null) {
                        throw new \SignWell\Sdk\Errors\ApiConnectionError(
                            sprintf(
                                '[%d] Error connecting to the API (%s)',
                                (int) $exception->getCode(),
                                $this->sanitizeRequestUri($request)
                            ),
                            (int) $exception->getCode(),
                            null,
                            null,
                            $exception
                        );
                    }

                    $statusCode = $response->getStatusCode();
                    $requestForMessage = $exception instanceof RequestException ? $exception->getRequest() : $request;
                    throw ApiException::fromResponse(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $this->sanitizeRequestUri($requestForMessage)
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        (string) $response->getBody(),
                        $exception
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMe'
     *
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getMe'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getMeRequest(string $contentType = self::contentTypes['getMe'][0])
    {


        $resourcePath = '/api/v1/me';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;





        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );

        // for model (json/xml)
        if ($httpBody === '' && count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Deserialize a successful response using the runtime-selected return type.
     *
     * @throws \SignWell\Sdk\ApiException
     */
    protected function deserializeResponse(ResponseInterface $response, Request $request, string $returnType): array
    {
        $statusCode = $response->getStatusCode();

        if ($returnType === '\SplFileObject') {
            $content = $response->getBody();
        } else {
            $content = (string) $response->getBody();
            if ($returnType !== 'string') {
                $contentType = $response->getHeaderLine('Content-Type');
                if ($contentType !== '' && !$this->headerSelector->isJsonMime($contentType)) {
                    throw new \SignWell\Sdk\Errors\UnsupportedContentTypeError(
                        sprintf('Content-Type is not supported: %s', $contentType),
                        $statusCode,
                        $response->getHeaders(),
                        $content
                    );
                }

                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw ApiException::fromResponse(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $this->sanitizeRequestUri($request)
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $content,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $returnType, $response->getHeaders()),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    protected function sanitizeRequestUri(RequestInterface $request): string
    {
        return (string) $request->getUri()->withQuery('')->withFragment('');
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
