<?php

declare(strict_types=1);
/**
 * RegionalApi
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Resources;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\ConnectException;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use Psr\Http\Message\RequestInterface;
use Psr\Http\Message\ResponseInterface;
use SignWell\Sdk\ApiException;
use SignWell\Sdk\Configuration;
use SignWell\Sdk\HeaderSelector;
use SignWell\Sdk\ObjectSerializer;

/**
 * RegionalApi Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class RegionalApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /** @var string[] $contentTypes **/
    public const contentTypes = [
        'getNom151Certificate' => [
            'application/json',
        ],
    ];

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $hostIndex (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ?ClientInterface $client = null,
        ?Configuration $config = null,
        ?HeaderSelector $selector = null,
        int $hostIndex = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: Configuration::getDefaultConfiguration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $hostIndex;
    }

    /**
     * Set the host index
     *
     * @param int $hostIndex Host index (required)
     */
    public function setHostIndex($hostIndex): void
    {
        $this->hostIndex = $hostIndex;
    }

    /**
     * Get the host index
     *
     * @return int Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation getNom151Certificate
     *
     * MX – NOM-151 Certificate
     *
     * @param  string $id id (required)
     * @param  bool|null $url_only If true, returns JSON with download URL instead of downloading the file (optional, default to false)
     * @param  bool|null $object_only object_only (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNom151Certificate'] to see the possible values for this operation
     *
     * @throws \SignWell\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return \SplFileObject|\SignWell\Sdk\Models\Nom151UrlResponse|\SignWell\Sdk\Models\Nom151CertificateResponse
     */
    public function getNom151Certificate($id, $url_only = false, $object_only = false, string $contentType = self::contentTypes['getNom151Certificate'][0])
    {
        list($response) = $this->getNom151CertificateWithHttpInfo($id, $url_only, $object_only, $contentType);
        return $response;
    }

    /**
     * Operation getNom151CertificateWithHttpInfo
     *
     * MX – NOM-151 Certificate
     *
     * @param  string $id (required)
     * @param  bool|null $url_only If true, returns JSON with download URL instead of downloading the file (optional, default to false)
     * @param  bool|null $object_only (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNom151Certificate'] to see the possible values for this operation
     *
     * @throws \SignWell\Sdk\ApiException on non-2xx response or if the response body is not in the expected format
     * @throws \InvalidArgumentException
     * @return array of \SplFileObject|\SignWell\Sdk\Models\Nom151UrlResponse|\SignWell\Sdk\Models\Nom151CertificateResponse, HTTP status code, HTTP response headers (array of strings)
     */
    public function getNom151CertificateWithHttpInfo($id, $url_only = false, $object_only = false, string $contentType = self::contentTypes['getNom151Certificate'][0])
    {
        $request = $this->getNom151CertificateRequest($id, $url_only, $object_only, $contentType);

        try {
            $options = $this->createHttpClientOption();
            $this->debugRequest($request);
            try {
                $response = $this->client->send($request, $options);
                $this->debugResponse($request, $response);
            } catch (RequestException|ConnectException $e) {
                $this->debugTransportError($request, $e);
                throw $this->createApiExceptionFromTransportException($e, $request);
            }

            $statusCode = $response->getStatusCode();
            $this->throwIfErrorResponse($response, $request);

            if ($url_only === true) {
                $returnType = '\SignWell\Sdk\Models\Nom151UrlResponse';
            } elseif ($object_only === true) {
                $returnType = '\SignWell\Sdk\Models\Nom151CertificateResponse';
            } else {
                $returnType = '\SplFileObject';
            }

            return $this->deserializeResponse($response, $request, $returnType);

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\Nom151UrlResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 404:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\ErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 422:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\ValidationErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
                case 429:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\SignWell\Sdk\Models\RateLimitErrorResponse',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getNom151CertificateAsync
     *
     * MX – NOM-151 Certificate
     *
     * @param  string $id (required)
     * @param  bool|null $url_only If true, returns JSON with download URL instead of downloading the file (optional, default to false)
     * @param  bool|null $object_only (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNom151Certificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNom151CertificateAsync($id, $url_only = false, $object_only = false, string $contentType = self::contentTypes['getNom151Certificate'][0])
    {
        return $this->getNom151CertificateAsyncWithHttpInfo($id, $url_only, $object_only, $contentType)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getNom151CertificateAsyncWithHttpInfo
     *
     * MX – NOM-151 Certificate
     *
     * @param  string $id (required)
     * @param  bool|null $url_only If true, returns JSON with download URL instead of downloading the file (optional, default to false)
     * @param  bool|null $object_only (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNom151Certificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getNom151CertificateAsyncWithHttpInfo($id, $url_only = false, $object_only = false, string $contentType = self::contentTypes['getNom151Certificate'][0])
    {
        if ($url_only === true) {
            $returnType = '\SignWell\Sdk\Models\Nom151UrlResponse';
        } elseif ($object_only === true) {
            $returnType = '\SignWell\Sdk\Models\Nom151CertificateResponse';
        } else {
            $returnType = '\SplFileObject';
        }
        $request = $this->getNom151CertificateRequest($id, $url_only, $object_only, $contentType);
        $options = $this->createHttpClientOption();
        $this->debugRequest($request);

        return $this->client
            ->sendAsync($request, $options)
            ->then(
                function (ResponseInterface $response) use ($request, $returnType) {
                    $this->debugResponse($request, $response);
                    $this->throwIfErrorResponse($response, $request);
                    return $this->deserializeResponse($response, $request, $returnType);
                },
                function ($exception) use ($request) {
                    $throwable = $exception instanceof \Throwable
                        ? $exception
                        : new \RuntimeException('Unexpected asynchronous transport error.');
                    $this->debugTransportError($request, $throwable);
                    throw $this->createApiExceptionFromTransportException($throwable, $request);
                }
            );
    }

    /**
     * Create request for operation 'getNom151Certificate'
     *
     * @param  string $id (required)
     * @param  bool|null $url_only If true, returns JSON with download URL instead of downloading the file (optional, default to false)
     * @param  bool|null $object_only (optional, default to false)
     * @param  string $contentType The value for the Content-Type header. Check self::contentTypes['getNom151Certificate'] to see the possible values for this operation
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    public function getNom151CertificateRequest($id, $url_only = false, $object_only = false, string $contentType = self::contentTypes['getNom151Certificate'][0])
    {

        // verify the required parameter 'id' is set
        if ($id === null || (is_array($id) && count($id) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $id when calling getNom151Certificate'
            );
        }



        if ($url_only === true && $object_only === true) {
            throw new \InvalidArgumentException('getNom151Certificate does not support url_only and object_only together.');
        }

        $resourcePath = '/api/v1/documents/{id}/nom151_certificate';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $url_only,
            'url_only', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);
        // query params
        $queryParams = array_merge($queryParams, ObjectSerializer::toQueryValue(
            $object_only,
            'object_only', // param base name
            'boolean', // openApiType
            'form', // style
            true, // explode
            false // required
        ) ?? []);


        // path params
        if ($id !== null) {
            $resourcePath = str_replace(
                '{' . 'id' . '}',
                ObjectSerializer::toPathValue($id),
                $resourcePath
            );
        }


        $headers = $this->headerSelector->selectHeaders(
            ['application/json', ],
            $contentType,
            $multipart
        );
        if ($url_only === true) {
            $headers['Accept'] = 'application/json';
        } elseif ($object_only === true) {
            $headers['Accept'] = 'application/json';
        } else {
            $headers['Accept'] = 'application/octet-stream';
        }

        // for model (json/xml)
        if ($httpBody === '' && count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $formParamValueItems = is_array($formParamValue) ? $formParamValue : [$formParamValue];
                    foreach ($formParamValueItems as $formParamValueItem) {
                        $multipartContents[] = [
                            'name' => $formParamName,
                            'contents' => $formParamValueItem
                        ];
                    }
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif (stripos($headers['Content-Type'], 'application/json') !== false) {
                # if Content-Type contains "application/json", json_encode the form parameters
                $httpBody = \GuzzleHttp\Utils::jsonEncode($formParams);
            } else {
                // for HTTP post (form)
                $httpBody = ObjectSerializer::buildQuery($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('X-Api-Key');
        if ($apiKey !== null) {
            $headers['X-Api-Key'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $operationHost = $this->config->getHost();
        $query = ObjectSerializer::buildQuery($queryParams);
        return new Request(
            'GET',
            $operationHost . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Deserialize a successful response using the runtime-selected return type.
     *
     * @throws \SignWell\Sdk\ApiException
     */
    protected function deserializeResponse(ResponseInterface $response, Request $request, string $returnType): array
    {
        $statusCode = $response->getStatusCode();

        if ($returnType === '\SplFileObject') {
            $content = $response->getBody();
        } else {
            $content = (string) $response->getBody();
            if ($returnType !== 'string') {
                $contentType = $response->getHeaderLine('Content-Type');
                if ($contentType !== '' && !$this->headerSelector->isJsonMime($contentType)) {
                    throw new \SignWell\Sdk\Errors\UnsupportedContentTypeError(
                        sprintf('Content-Type is not supported: %s', $contentType),
                        $statusCode,
                        $response->getHeaders(),
                        $content
                    );
                }

                try {
                    $content = json_decode($content, false, 512, JSON_THROW_ON_ERROR);
                } catch (\JsonException $exception) {
                    throw ApiException::fromResponse(
                        sprintf(
                            'Error JSON decoding server response (%s)',
                            $this->sanitizeRequestUri($request)
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $content,
                        $exception
                    );
                }
            }
        }

        return [
            ObjectSerializer::deserialize($content, $returnType, $response->getHeaders()),
            $response->getStatusCode(),
            $response->getHeaders(),
        ];
    }

    protected function sanitizeRequestUri(RequestInterface $request): string
    {
        return (string) $request->getUri()->withQuery('')->withFragment('');
    }

    protected function throwIfErrorResponse(ResponseInterface $response, RequestInterface $request): void
    {
        $statusCode = $response->getStatusCode();
        if ($statusCode < 200 || $statusCode > 299) {
            throw ApiException::fromResponse(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $statusCode,
                    $this->sanitizeRequestUri($request)
                ),
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody()
            );
        }
    }

    protected function createApiExceptionFromTransportException(\Throwable $exception, RequestInterface $request): ApiException
    {
        $response = $exception instanceof RequestException ? $exception->getResponse() : null;
        if ($response !== null) {
            $statusCode = $response->getStatusCode();
            $requestForMessage = $exception instanceof RequestException ? $exception->getRequest() : $request;

            return ApiException::fromResponse(
                sprintf(
                    '[%d] Error connecting to the API (%s)',
                    $statusCode,
                    $this->sanitizeRequestUri($requestForMessage)
                ),
                $statusCode,
                $response->getHeaders(),
                (string) $response->getBody(),
                $exception
            );
        }

        $errorClass = $this->isTimeoutException($exception)
            ? \SignWell\Sdk\Errors\ApiTimeoutError::class
            : \SignWell\Sdk\Errors\ApiConnectionError::class;

        return new $errorClass(
            sprintf(
                '[%d] Error connecting to the API (%s)',
                (int) $exception->getCode(),
                $this->sanitizeRequestUri($request)
            ),
            (int) $exception->getCode(),
            null,
            null,
            $exception
        );
    }

    protected function isTimeoutException(\Throwable $exception): bool
    {
        if (method_exists($exception, 'getHandlerContext')) {
            $context = $exception->getHandlerContext();
            $errno = $context['errno'] ?? null;
            if ((int) $errno === 28) {
                return true;
            }
        }

        $message = strtolower($exception->getMessage());

        return str_contains($message, 'timed out') || str_contains($message, 'timeout');
    }

    protected function debugRequest(RequestInterface $request): void
    {
        if (!$this->config->getDebug()) {
            return;
        }

        $this->writeDebugLine(sprintf('Request: %s %s', $request->getMethod(), $this->sanitizeRequestUri($request)));
        $this->writeDebugLine('Request headers: ' . $this->encodedHeaders($request->getHeaders()));
    }

    protected function debugResponse(RequestInterface $request, ResponseInterface $response): void
    {
        if (!$this->config->getDebug()) {
            return;
        }

        $this->writeDebugLine(sprintf(
            'Response: %d %s',
            $response->getStatusCode(),
            $this->sanitizeRequestUri($request)
        ));
        $this->writeDebugLine('Response headers: ' . $this->encodedHeaders($response->getHeaders()));
    }

    protected function debugTransportError(RequestInterface $request, \Throwable $exception): void
    {
        if (!$this->config->getDebug()) {
            return;
        }

        $this->writeDebugLine(sprintf(
            'Transport error: %s code=%d timeout=%s uri=%s',
            $exception::class,
            (int) $exception->getCode(),
            $this->isTimeoutException($exception) ? 'true' : 'false',
            $this->sanitizeRequestUri($request)
        ));
    }

    /**
     * @param string[][] $headers
     */
    protected function encodedHeaders(array $headers): string
    {
        $encoded = json_encode($this->redactHeaders($headers), JSON_UNESCAPED_SLASHES);

        return is_string($encoded) ? $encoded : '{}';
    }

    /**
     * @param string[][] $headers
     * @return string[][]
     */
    protected function redactHeaders(array $headers): array
    {
        $redacted = [];
        foreach ($headers as $name => $values) {
            $redacted[$name] = in_array(strtolower((string) $name), ['authorization', 'proxy-authorization', 'x-api-key'], true)
                ? ['[REDACTED]']
                : $values;
        }

        return $redacted;
    }

    protected function writeDebugLine(string $line): void
    {
        $handle = fopen($this->config->getDebugFile(), 'a');
        if (!$handle) {
            throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
        }

        try {
            fwrite($handle, '[' . date('c') . '] ' . $line . PHP_EOL);
        } finally {
            fclose($handle);
        }
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        return [
            RequestOptions::CONNECT_TIMEOUT => $this->config->getConnectTimeout(),
            RequestOptions::TIMEOUT => $this->config->getTimeout(),
        ];
    }
}
