<?php

declare(strict_types=1);
/**
 * AccountInfoResponsePreferences
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * AccountInfoResponsePreferences Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class AccountInfoResponsePreferences implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'AccountInfoResponse_preferences';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'date_format' => 'string',
        'days_until_links_expire' => 'int',
        'disable_apply_everywhere' => 'bool',
        'disable_apply_everywhere_effective' => 'bool',
        'disable_drawn_signatures' => 'bool',
        'disable_typed_signatures' => 'bool',
        'disable_uploaded_signatures' => 'bool',
        'enable_redirect' => 'bool',
        'hide_document_id_in_audit' => 'bool',
        'mute_branding' => 'bool',
        'redirect_url' => 'string',
        'separate_audit_pdf' => 'bool',
        'separate_completed_file' => 'bool',
        'enable_nom151_compliance' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'date_format' => null,
        'days_until_links_expire' => null,
        'disable_apply_everywhere' => null,
        'disable_apply_everywhere_effective' => null,
        'disable_drawn_signatures' => null,
        'disable_typed_signatures' => null,
        'disable_uploaded_signatures' => null,
        'enable_redirect' => null,
        'hide_document_id_in_audit' => null,
        'mute_branding' => null,
        'redirect_url' => null,
        'separate_audit_pdf' => null,
        'separate_completed_file' => null,
        'enable_nom151_compliance' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'date_format' => false,
        'days_until_links_expire' => false,
        'disable_apply_everywhere' => false,
        'disable_apply_everywhere_effective' => false,
        'disable_drawn_signatures' => false,
        'disable_typed_signatures' => false,
        'disable_uploaded_signatures' => false,
        'enable_redirect' => false,
        'hide_document_id_in_audit' => false,
        'mute_branding' => false,
        'redirect_url' => true,
        'separate_audit_pdf' => false,
        'separate_completed_file' => false,
        'enable_nom151_compliance' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'date_format' => 'date_format',
        'days_until_links_expire' => 'days_until_links_expire',
        'disable_apply_everywhere' => 'disable_apply_everywhere',
        'disable_apply_everywhere_effective' => 'disable_apply_everywhere_effective',
        'disable_drawn_signatures' => 'disable_drawn_signatures',
        'disable_typed_signatures' => 'disable_typed_signatures',
        'disable_uploaded_signatures' => 'disable_uploaded_signatures',
        'enable_redirect' => 'enable_redirect',
        'hide_document_id_in_audit' => 'hide_document_id_in_audit',
        'mute_branding' => 'mute_branding',
        'redirect_url' => 'redirect_url',
        'separate_audit_pdf' => 'separate_audit_pdf',
        'separate_completed_file' => 'separate_completed_file',
        'enable_nom151_compliance' => 'enable_nom151_compliance'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'date_format' => 'setDateFormat',
        'days_until_links_expire' => 'setDaysUntilLinksExpire',
        'disable_apply_everywhere' => 'setDisableApplyEverywhere',
        'disable_apply_everywhere_effective' => 'setDisableApplyEverywhereEffective',
        'disable_drawn_signatures' => 'setDisableDrawnSignatures',
        'disable_typed_signatures' => 'setDisableTypedSignatures',
        'disable_uploaded_signatures' => 'setDisableUploadedSignatures',
        'enable_redirect' => 'setEnableRedirect',
        'hide_document_id_in_audit' => 'setHideDocumentIdInAudit',
        'mute_branding' => 'setMuteBranding',
        'redirect_url' => 'setRedirectUrl',
        'separate_audit_pdf' => 'setSeparateAuditPdf',
        'separate_completed_file' => 'setSeparateCompletedFile',
        'enable_nom151_compliance' => 'setEnableNom151Compliance'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'date_format' => 'getDateFormat',
        'days_until_links_expire' => 'getDaysUntilLinksExpire',
        'disable_apply_everywhere' => 'getDisableApplyEverywhere',
        'disable_apply_everywhere_effective' => 'getDisableApplyEverywhereEffective',
        'disable_drawn_signatures' => 'getDisableDrawnSignatures',
        'disable_typed_signatures' => 'getDisableTypedSignatures',
        'disable_uploaded_signatures' => 'getDisableUploadedSignatures',
        'enable_redirect' => 'getEnableRedirect',
        'hide_document_id_in_audit' => 'getHideDocumentIdInAudit',
        'mute_branding' => 'getMuteBranding',
        'redirect_url' => 'getRedirectUrl',
        'separate_audit_pdf' => 'getSeparateAuditPdf',
        'separate_completed_file' => 'getSeparateCompletedFile',
        'enable_nom151_compliance' => 'getEnableNom151Compliance'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('date_format', $data ?? [], null);
        $this->setIfExists('days_until_links_expire', $data ?? [], null);
        $this->setIfExists('disable_apply_everywhere', $data ?? [], null);
        $this->setIfExists('disable_apply_everywhere_effective', $data ?? [], null);
        $this->setIfExists('disable_drawn_signatures', $data ?? [], null);
        $this->setIfExists('disable_typed_signatures', $data ?? [], null);
        $this->setIfExists('disable_uploaded_signatures', $data ?? [], null);
        $this->setIfExists('enable_redirect', $data ?? [], null);
        $this->setIfExists('hide_document_id_in_audit', $data ?? [], null);
        $this->setIfExists('mute_branding', $data ?? [], null);
        $this->setIfExists('redirect_url', $data ?? [], null);
        $this->setIfExists('separate_audit_pdf', $data ?? [], null);
        $this->setIfExists('separate_completed_file', $data ?? [], null);
        $this->setIfExists('enable_nom151_compliance', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets date_format
     *
     * @return string|null
     */
    public function getDateFormat()
    {
        return $this->container['date_format'];
    }

    /**
     * Sets date_format
     *
     * @param string|null $date_format date_format
     *
     * @return self
     */
    public function setDateFormat($date_format)
    {
        if (is_null($date_format)) {
            throw new \InvalidArgumentException('non-nullable date_format cannot be null');
        }
        $this->container['date_format'] = $date_format;

        return $this;
    }

    /**
     * Gets days_until_links_expire
     *
     * @return int|null
     */
    public function getDaysUntilLinksExpire()
    {
        return $this->container['days_until_links_expire'];
    }

    /**
     * Sets days_until_links_expire
     *
     * @param int|null $days_until_links_expire days_until_links_expire
     *
     * @return self
     */
    public function setDaysUntilLinksExpire($days_until_links_expire)
    {
        if (is_null($days_until_links_expire)) {
            throw new \InvalidArgumentException('non-nullable days_until_links_expire cannot be null');
        }
        $this->container['days_until_links_expire'] = $days_until_links_expire;

        return $this;
    }

    /**
     * Gets disable_apply_everywhere
     *
     * @return bool|null
     */
    public function getDisableApplyEverywhere()
    {
        return $this->container['disable_apply_everywhere'];
    }

    /**
     * Sets disable_apply_everywhere
     *
     * @param bool|null $disable_apply_everywhere disable_apply_everywhere
     *
     * @return self
     */
    public function setDisableApplyEverywhere($disable_apply_everywhere)
    {
        if (is_null($disable_apply_everywhere)) {
            throw new \InvalidArgumentException('non-nullable disable_apply_everywhere cannot be null');
        }
        $this->container['disable_apply_everywhere'] = $disable_apply_everywhere;

        return $this;
    }

    /**
     * Gets disable_apply_everywhere_effective
     *
     * @return bool|null
     */
    public function getDisableApplyEverywhereEffective()
    {
        return $this->container['disable_apply_everywhere_effective'];
    }

    /**
     * Sets disable_apply_everywhere_effective
     *
     * @param bool|null $disable_apply_everywhere_effective disable_apply_everywhere_effective
     *
     * @return self
     */
    public function setDisableApplyEverywhereEffective($disable_apply_everywhere_effective)
    {
        if (is_null($disable_apply_everywhere_effective)) {
            throw new \InvalidArgumentException('non-nullable disable_apply_everywhere_effective cannot be null');
        }
        $this->container['disable_apply_everywhere_effective'] = $disable_apply_everywhere_effective;

        return $this;
    }

    /**
     * Gets disable_drawn_signatures
     *
     * @return bool|null
     */
    public function getDisableDrawnSignatures()
    {
        return $this->container['disable_drawn_signatures'];
    }

    /**
     * Sets disable_drawn_signatures
     *
     * @param bool|null $disable_drawn_signatures disable_drawn_signatures
     *
     * @return self
     */
    public function setDisableDrawnSignatures($disable_drawn_signatures)
    {
        if (is_null($disable_drawn_signatures)) {
            throw new \InvalidArgumentException('non-nullable disable_drawn_signatures cannot be null');
        }
        $this->container['disable_drawn_signatures'] = $disable_drawn_signatures;

        return $this;
    }

    /**
     * Gets disable_typed_signatures
     *
     * @return bool|null
     */
    public function getDisableTypedSignatures()
    {
        return $this->container['disable_typed_signatures'];
    }

    /**
     * Sets disable_typed_signatures
     *
     * @param bool|null $disable_typed_signatures disable_typed_signatures
     *
     * @return self
     */
    public function setDisableTypedSignatures($disable_typed_signatures)
    {
        if (is_null($disable_typed_signatures)) {
            throw new \InvalidArgumentException('non-nullable disable_typed_signatures cannot be null');
        }
        $this->container['disable_typed_signatures'] = $disable_typed_signatures;

        return $this;
    }

    /**
     * Gets disable_uploaded_signatures
     *
     * @return bool|null
     */
    public function getDisableUploadedSignatures()
    {
        return $this->container['disable_uploaded_signatures'];
    }

    /**
     * Sets disable_uploaded_signatures
     *
     * @param bool|null $disable_uploaded_signatures disable_uploaded_signatures
     *
     * @return self
     */
    public function setDisableUploadedSignatures($disable_uploaded_signatures)
    {
        if (is_null($disable_uploaded_signatures)) {
            throw new \InvalidArgumentException('non-nullable disable_uploaded_signatures cannot be null');
        }
        $this->container['disable_uploaded_signatures'] = $disable_uploaded_signatures;

        return $this;
    }

    /**
     * Gets enable_redirect
     *
     * @return bool|null
     */
    public function getEnableRedirect()
    {
        return $this->container['enable_redirect'];
    }

    /**
     * Sets enable_redirect
     *
     * @param bool|null $enable_redirect enable_redirect
     *
     * @return self
     */
    public function setEnableRedirect($enable_redirect)
    {
        if (is_null($enable_redirect)) {
            throw new \InvalidArgumentException('non-nullable enable_redirect cannot be null');
        }
        $this->container['enable_redirect'] = $enable_redirect;

        return $this;
    }

    /**
     * Gets hide_document_id_in_audit
     *
     * @return bool|null
     */
    public function getHideDocumentIdInAudit()
    {
        return $this->container['hide_document_id_in_audit'];
    }

    /**
     * Sets hide_document_id_in_audit
     *
     * @param bool|null $hide_document_id_in_audit hide_document_id_in_audit
     *
     * @return self
     */
    public function setHideDocumentIdInAudit($hide_document_id_in_audit)
    {
        if (is_null($hide_document_id_in_audit)) {
            throw new \InvalidArgumentException('non-nullable hide_document_id_in_audit cannot be null');
        }
        $this->container['hide_document_id_in_audit'] = $hide_document_id_in_audit;

        return $this;
    }

    /**
     * Gets mute_branding
     *
     * @return bool|null
     */
    public function getMuteBranding()
    {
        return $this->container['mute_branding'];
    }

    /**
     * Sets mute_branding
     *
     * @param bool|null $mute_branding mute_branding
     *
     * @return self
     */
    public function setMuteBranding($mute_branding)
    {
        if (is_null($mute_branding)) {
            throw new \InvalidArgumentException('non-nullable mute_branding cannot be null');
        }
        $this->container['mute_branding'] = $mute_branding;

        return $this;
    }

    /**
     * Gets redirect_url
     *
     * @return string|null
     */
    public function getRedirectUrl()
    {
        return $this->container['redirect_url'];
    }

    /**
     * Sets redirect_url
     *
     * @param string|null $redirect_url redirect_url
     *
     * @return self
     */
    public function setRedirectUrl($redirect_url)
    {
        if (is_null($redirect_url)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_url'] = $redirect_url;

        return $this;
    }

    /**
     * Gets separate_audit_pdf
     *
     * @return bool|null
     */
    public function getSeparateAuditPdf()
    {
        return $this->container['separate_audit_pdf'];
    }

    /**
     * Sets separate_audit_pdf
     *
     * @param bool|null $separate_audit_pdf separate_audit_pdf
     *
     * @return self
     */
    public function setSeparateAuditPdf($separate_audit_pdf)
    {
        if (is_null($separate_audit_pdf)) {
            throw new \InvalidArgumentException('non-nullable separate_audit_pdf cannot be null');
        }
        $this->container['separate_audit_pdf'] = $separate_audit_pdf;

        return $this;
    }

    /**
     * Gets separate_completed_file
     *
     * @return bool|null
     */
    public function getSeparateCompletedFile()
    {
        return $this->container['separate_completed_file'];
    }

    /**
     * Sets separate_completed_file
     *
     * @param bool|null $separate_completed_file separate_completed_file
     *
     * @return self
     */
    public function setSeparateCompletedFile($separate_completed_file)
    {
        if (is_null($separate_completed_file)) {
            throw new \InvalidArgumentException('non-nullable separate_completed_file cannot be null');
        }
        $this->container['separate_completed_file'] = $separate_completed_file;

        return $this;
    }

    /**
     * Gets enable_nom151_compliance
     *
     * @return bool|null
     */
    public function getEnableNom151Compliance()
    {
        return $this->container['enable_nom151_compliance'];
    }

    /**
     * Sets enable_nom151_compliance
     *
     * @param bool|null $enable_nom151_compliance enable_nom151_compliance
     *
     * @return self
     */
    public function setEnableNom151Compliance($enable_nom151_compliance)
    {
        if (is_null($enable_nom151_compliance)) {
            throw new \InvalidArgumentException('non-nullable enable_nom151_compliance cannot be null');
        }
        $this->container['enable_nom151_compliance'] = $enable_nom151_compliance;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
