<?php

declare(strict_types=1);
/**
 * BulkSendValidateCsvResponse
 *
 * PHP version 7.4
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * BulkSendValidateCsvResponse Class Doc Comment
 *
 * @category Class
 * @description Validated bulk send CSV response with defaults applied
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class BulkSendValidateCsvResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'BulkSendValidateCsvResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'bulk_send_csv' => 'string',
        'template_ids' => 'string[]',
        'skip_row_errors' => 'bool',
        'api_application_id' => 'string',
        'name' => 'string',
        'subject' => 'string',
        'message' => 'string',
        'apply_signing_order' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'bulk_send_csv' => null,
        'template_ids' => 'uuid',
        'skip_row_errors' => null,
        'api_application_id' => 'uuid',
        'name' => null,
        'subject' => null,
        'message' => null,
        'apply_signing_order' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'bulk_send_csv' => false,
        'template_ids' => false,
        'skip_row_errors' => false,
        'api_application_id' => true,
        'name' => false,
        'subject' => false,
        'message' => false,
        'apply_signing_order' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'bulk_send_csv' => 'bulk_send_csv',
        'template_ids' => 'template_ids',
        'skip_row_errors' => 'skip_row_errors',
        'api_application_id' => 'api_application_id',
        'name' => 'name',
        'subject' => 'subject',
        'message' => 'message',
        'apply_signing_order' => 'apply_signing_order'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'bulk_send_csv' => 'setBulkSendCsv',
        'template_ids' => 'setTemplateIds',
        'skip_row_errors' => 'setSkipRowErrors',
        'api_application_id' => 'setApiApplicationId',
        'name' => 'setName',
        'subject' => 'setSubject',
        'message' => 'setMessage',
        'apply_signing_order' => 'setApplySigningOrder'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'bulk_send_csv' => 'getBulkSendCsv',
        'template_ids' => 'getTemplateIds',
        'skip_row_errors' => 'getSkipRowErrors',
        'api_application_id' => 'getApiApplicationId',
        'name' => 'getName',
        'subject' => 'getSubject',
        'message' => 'getMessage',
        'apply_signing_order' => 'getApplySigningOrder'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('bulk_send_csv', $data ?? [], null);
        $this->setIfExists('template_ids', $data ?? [], null);
        $this->setIfExists('skip_row_errors', $data ?? [], null);
        $this->setIfExists('api_application_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('apply_signing_order', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['bulk_send_csv'] === null) {
            $invalidProperties[] = "'bulk_send_csv' can't be null";
        }
        if ($this->container['template_ids'] === null) {
            $invalidProperties[] = "'template_ids' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets bulk_send_csv
     *
     * @return string
     */
    public function getBulkSendCsv()
    {
        return $this->container['bulk_send_csv'];
    }

    /**
     * Sets bulk_send_csv
     *
     * @param string $bulk_send_csv Base64-encoded CSV content
     *
     * @return self
     */
    public function setBulkSendCsv($bulk_send_csv)
    {
        if (is_null($bulk_send_csv)) {
            throw new \InvalidArgumentException('non-nullable bulk_send_csv cannot be null');
        }
        $this->container['bulk_send_csv'] = $bulk_send_csv;

        return $this;
    }

    /**
     * Gets template_ids
     *
     * @return string[]
     */
    public function getTemplateIds()
    {
        return $this->container['template_ids'];
    }

    /**
     * Sets template_ids
     *
     * @param string[] $template_ids template_ids
     *
     * @return self
     */
    public function setTemplateIds($template_ids)
    {
        if (is_null($template_ids)) {
            throw new \InvalidArgumentException('non-nullable template_ids cannot be null');
        }
        $this->container['template_ids'] = $template_ids;

        return $this;
    }

    /**
     * Gets skip_row_errors
     *
     * @return bool|null
     */
    public function getSkipRowErrors()
    {
        return $this->container['skip_row_errors'];
    }

    /**
     * Sets skip_row_errors
     *
     * @param bool|null $skip_row_errors skip_row_errors
     *
     * @return self
     */
    public function setSkipRowErrors($skip_row_errors)
    {
        if (is_null($skip_row_errors)) {
            throw new \InvalidArgumentException('non-nullable skip_row_errors cannot be null');
        }
        $this->container['skip_row_errors'] = $skip_row_errors;

        return $this;
    }

    /**
     * Gets api_application_id
     *
     * @return string|null
     */
    public function getApiApplicationId()
    {
        return $this->container['api_application_id'];
    }

    /**
     * Sets api_application_id
     *
     * @param string|null $api_application_id api_application_id
     *
     * @return self
     */
    public function setApiApplicationId($api_application_id)
    {
        if (is_null($api_application_id)) {
            array_push($this->openAPINullablesSetToNull, 'api_application_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_application_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_application_id'] = $api_application_id;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets apply_signing_order
     *
     * @return bool|null
     */
    public function getApplySigningOrder()
    {
        return $this->container['apply_signing_order'];
    }

    /**
     * Sets apply_signing_order
     *
     * @param bool|null $apply_signing_order apply_signing_order
     *
     * @return self
     */
    public function setApplySigningOrder($apply_signing_order)
    {
        if (is_null($apply_signing_order)) {
            throw new \InvalidArgumentException('non-nullable apply_signing_order cannot be null');
        }
        $this->container['apply_signing_order'] = $apply_signing_order;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
