<?php

declare(strict_types=1);
/**
 * CheckboxValidation
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

/**
 * CheckboxValidation Class Doc Comment
 *
 * @category Class
 * @description Validation rule for checkbox groups
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class CheckboxValidation
{
    /**
     * Possible values of this enum
     */
    public const MINIMUM = 'minimum';

    public const MAXIMUM = 'maximum';

    public const RANGE = 'range';

    public const EXACT = 'exact';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MINIMUM,
            self::MAXIMUM,
            self::RANGE,
            self::EXACT,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}
