<?php

declare(strict_types=1);
/**
 * DateFormat
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

/**
 * DateFormat Class Doc Comment
 *
 * @category Class
 * @description Date format for date fields. Valid values: MM/DD/YYYY, DD/MM/YYYY, YYYY/MM/DD, Month DD, YYYY, MM/DD/YYYY hh:mm:ss a. Default: MM/DD/YYYY
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class DateFormat
{
    /**
     * Possible values of this enum
     */
    public const MM_DD_YYYY = 'MM/DD/YYYY';

    public const DD_MM_YYYY = 'DD/MM/YYYY';

    public const YYYY_MM_DD = 'YYYY/MM/DD';

    public const MONTH_DD_YYYY = 'Month DD, YYYY';

    public const MM_DD_YYYY_HH_MM_SS_A = 'MM/DD/YYYY hh:mm:ss a';

    public const UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api';

    /**
     * Gets allowable values of the enum
     * @return string[]
     */
    public static function getAllowableEnumValues()
    {
        return [
            self::MM_DD_YYYY,
            self::DD_MM_YYYY,
            self::YYYY_MM_DD,
            self::MONTH_DD_YYYY,
            self::MM_DD_YYYY_HH_MM_SS_A,
            self::UNKNOWN_DEFAULT_OPEN_API
        ];
    }
}
