<?php

declare(strict_types=1);
/**
 * DocumentRequest
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * DocumentRequest Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentRequest implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'test_mode' => 'bool',
        'files' => '\SignWell\Sdk\Models\FilesInner[]',
        'name' => 'string',
        'subject' => 'string',
        'message' => 'string',
        'recipients' => '\SignWell\Sdk\Models\RecipientsInner[]',
        'draft' => 'bool',
        'self_sign' => 'bool',
        'with_signature_page' => 'bool',
        'expires_in' => 'int',
        'reminders' => 'bool',
        'apply_signing_order' => 'bool',
        'api_application_id' => 'string',
        'embedded_signing' => 'bool',
        'embedded_signing_notifications' => 'bool',
        'text_tags' => 'bool',
        'custom_requester_name' => 'string',
        'custom_requester_email' => 'string',
        'redirect_url' => 'string',
        'allow_decline' => 'bool',
        'allow_reassign' => 'bool',
        'decline_redirect_url' => 'string',
        'language' => 'string',
        'metadata' => 'array<string,string>',
        'fields' => '\SignWell\Sdk\Models\FieldsInnerInner[][]',
        'attachment_requests' => '\SignWell\Sdk\Models\AttachmentRequestsInner[]',
        'copied_contacts' => '\SignWell\Sdk\Models\CopiedContactsInner[]',
        'labels' => '\SignWell\Sdk\Models\LabelRequest[]',
        'checkbox_groups' => '\SignWell\Sdk\Models\CheckboxGroupsInner[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'test_mode' => null,
        'files' => null,
        'name' => null,
        'subject' => null,
        'message' => null,
        'recipients' => null,
        'draft' => null,
        'self_sign' => null,
        'with_signature_page' => null,
        'expires_in' => null,
        'reminders' => null,
        'apply_signing_order' => null,
        'api_application_id' => 'uuid',
        'embedded_signing' => null,
        'embedded_signing_notifications' => null,
        'text_tags' => null,
        'custom_requester_name' => null,
        'custom_requester_email' => 'email',
        'redirect_url' => 'url',
        'allow_decline' => null,
        'allow_reassign' => null,
        'decline_redirect_url' => 'url',
        'language' => null,
        'metadata' => null,
        'fields' => null,
        'attachment_requests' => null,
        'copied_contacts' => null,
        'labels' => null,
        'checkbox_groups' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'test_mode' => false,
        'files' => false,
        'name' => false,
        'subject' => false,
        'message' => false,
        'recipients' => false,
        'draft' => false,
        'self_sign' => false,
        'with_signature_page' => false,
        'expires_in' => false,
        'reminders' => false,
        'apply_signing_order' => false,
        'api_application_id' => false,
        'embedded_signing' => false,
        'embedded_signing_notifications' => false,
        'text_tags' => false,
        'custom_requester_name' => false,
        'custom_requester_email' => false,
        'redirect_url' => false,
        'allow_decline' => false,
        'allow_reassign' => false,
        'decline_redirect_url' => false,
        'language' => false,
        'metadata' => false,
        'fields' => false,
        'attachment_requests' => false,
        'copied_contacts' => false,
        'labels' => false,
        'checkbox_groups' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'test_mode' => 'test_mode',
        'files' => 'files',
        'name' => 'name',
        'subject' => 'subject',
        'message' => 'message',
        'recipients' => 'recipients',
        'draft' => 'draft',
        'self_sign' => 'self_sign',
        'with_signature_page' => 'with_signature_page',
        'expires_in' => 'expires_in',
        'reminders' => 'reminders',
        'apply_signing_order' => 'apply_signing_order',
        'api_application_id' => 'api_application_id',
        'embedded_signing' => 'embedded_signing',
        'embedded_signing_notifications' => 'embedded_signing_notifications',
        'text_tags' => 'text_tags',
        'custom_requester_name' => 'custom_requester_name',
        'custom_requester_email' => 'custom_requester_email',
        'redirect_url' => 'redirect_url',
        'allow_decline' => 'allow_decline',
        'allow_reassign' => 'allow_reassign',
        'decline_redirect_url' => 'decline_redirect_url',
        'language' => 'language',
        'metadata' => 'metadata',
        'fields' => 'fields',
        'attachment_requests' => 'attachment_requests',
        'copied_contacts' => 'copied_contacts',
        'labels' => 'labels',
        'checkbox_groups' => 'checkbox_groups'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'test_mode' => 'setTestMode',
        'files' => 'setFiles',
        'name' => 'setName',
        'subject' => 'setSubject',
        'message' => 'setMessage',
        'recipients' => 'setRecipients',
        'draft' => 'setDraft',
        'self_sign' => 'setSelfSign',
        'with_signature_page' => 'setWithSignaturePage',
        'expires_in' => 'setExpiresIn',
        'reminders' => 'setReminders',
        'apply_signing_order' => 'setApplySigningOrder',
        'api_application_id' => 'setApiApplicationId',
        'embedded_signing' => 'setEmbeddedSigning',
        'embedded_signing_notifications' => 'setEmbeddedSigningNotifications',
        'text_tags' => 'setTextTags',
        'custom_requester_name' => 'setCustomRequesterName',
        'custom_requester_email' => 'setCustomRequesterEmail',
        'redirect_url' => 'setRedirectUrl',
        'allow_decline' => 'setAllowDecline',
        'allow_reassign' => 'setAllowReassign',
        'decline_redirect_url' => 'setDeclineRedirectUrl',
        'language' => 'setLanguage',
        'metadata' => 'setMetadata',
        'fields' => 'setFields',
        'attachment_requests' => 'setAttachmentRequests',
        'copied_contacts' => 'setCopiedContacts',
        'labels' => 'setLabels',
        'checkbox_groups' => 'setCheckboxGroups'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'test_mode' => 'getTestMode',
        'files' => 'getFiles',
        'name' => 'getName',
        'subject' => 'getSubject',
        'message' => 'getMessage',
        'recipients' => 'getRecipients',
        'draft' => 'getDraft',
        'self_sign' => 'getSelfSign',
        'with_signature_page' => 'getWithSignaturePage',
        'expires_in' => 'getExpiresIn',
        'reminders' => 'getReminders',
        'apply_signing_order' => 'getApplySigningOrder',
        'api_application_id' => 'getApiApplicationId',
        'embedded_signing' => 'getEmbeddedSigning',
        'embedded_signing_notifications' => 'getEmbeddedSigningNotifications',
        'text_tags' => 'getTextTags',
        'custom_requester_name' => 'getCustomRequesterName',
        'custom_requester_email' => 'getCustomRequesterEmail',
        'redirect_url' => 'getRedirectUrl',
        'allow_decline' => 'getAllowDecline',
        'allow_reassign' => 'getAllowReassign',
        'decline_redirect_url' => 'getDeclineRedirectUrl',
        'language' => 'getLanguage',
        'metadata' => 'getMetadata',
        'fields' => 'getFields',
        'attachment_requests' => 'getAttachmentRequests',
        'copied_contacts' => 'getCopiedContacts',
        'labels' => 'getLabels',
        'checkbox_groups' => 'getCheckboxGroups'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('test_mode', $data ?? [], false);
        $this->setIfExists('files', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('draft', $data ?? [], false);
        $this->setIfExists('self_sign', $data ?? [], false);
        $this->setIfExists('with_signature_page', $data ?? [], false);
        $this->setIfExists('expires_in', $data ?? [], null);
        $this->setIfExists('reminders', $data ?? [], true);
        $this->setIfExists('apply_signing_order', $data ?? [], false);
        $this->setIfExists('api_application_id', $data ?? [], null);
        $this->setIfExists('embedded_signing', $data ?? [], false);
        $this->setIfExists('embedded_signing_notifications', $data ?? [], false);
        $this->setIfExists('text_tags', $data ?? [], false);
        $this->setIfExists('custom_requester_name', $data ?? [], null);
        $this->setIfExists('custom_requester_email', $data ?? [], null);
        $this->setIfExists('redirect_url', $data ?? [], null);
        $this->setIfExists('allow_decline', $data ?? [], true);
        $this->setIfExists('allow_reassign', $data ?? [], true);
        $this->setIfExists('decline_redirect_url', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('attachment_requests', $data ?? [], null);
        $this->setIfExists('copied_contacts', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('checkbox_groups', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['files'] === null) {
            $invalidProperties[] = "'files' can't be null";
        }
        if ($this->container['recipients'] === null) {
            $invalidProperties[] = "'recipients' can't be null";
        }
        if (!is_null($this->container['expires_in']) && ($this->container['expires_in'] < 1)) {
            $invalidProperties[] = "invalid value for 'expires_in', must be bigger than or equal to 1.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets test_mode
     *
     * @return bool|null
     */
    public function getTestMode()
    {
        return $this->container['test_mode'];
    }

    /**
     * Sets test_mode
     *
     * @param bool|null $test_mode Set to `true` to enable Test Mode. Documents created with Test Mode do not count towards API billing and are not legally binding. Defaults to `false`
     *
     * @return self
     */
    public function setTestMode($test_mode)
    {
        if (is_null($test_mode)) {
            throw new \InvalidArgumentException('non-nullable test_mode cannot be null');
        }
        $this->container['test_mode'] = $test_mode;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \SignWell\Sdk\Models\FilesInner[]
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \SignWell\Sdk\Models\FilesInner[] $files Document files can be uploaded by specifying a file URL or base64 string. Either `file_url` or `file_base64` must be present (not both). Valid file types are: .pdf, .doc, .docx, .pages, .ppt, .pptx, .key, .xls, .xlsx, .numbers, .jpg, .jpeg, .png, .tiff, .tif, .webp, .html, and .htm
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            throw new \InvalidArgumentException('non-nullable files cannot be null');
        }
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name The name of the document.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject Email subject for the signature request that recipients will see. Defaults to the default system subject or a template subject (if the document is created from a template).
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message Email message for the signature request that recipients will see. Defaults to the default system message or a template message (if the document is created from a template).
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \SignWell\Sdk\Models\RecipientsInner[]
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \SignWell\Sdk\Models\RecipientsInner[] $recipients Document recipients are people that must complete and/or sign a document.
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets draft
     *
     * @return bool|null
     */
    public function getDraft()
    {
        return $this->container['draft'];
    }

    /**
     * Sets draft
     *
     * @param bool|null $draft Whether the document can still be updated before sending a signature request. If set to `false` the document is sent for signing as part of this request. Defaults to `false`.
     *
     * @return self
     */
    public function setDraft($draft)
    {
        if (is_null($draft)) {
            throw new \InvalidArgumentException('non-nullable draft cannot be null');
        }
        $this->container['draft'] = $draft;

        return $this;
    }

    /**
     * Gets self_sign
     *
     * @return bool|null
     */
    public function getSelfSign()
    {
        return $this->container['self_sign'];
    }

    /**
     * Sets self_sign
     *
     * @param bool|null $self_sign When set to true the document will enter self-sign mode, which allows the document creator to sign and complete a document without any field setup. Must use the embedded_edit_url in the response and (if embedding) the embedded requesting workflow.
     *
     * @return self
     */
    public function setSelfSign($self_sign)
    {
        if (is_null($self_sign)) {
            throw new \InvalidArgumentException('non-nullable self_sign cannot be null');
        }
        $this->container['self_sign'] = $self_sign;

        return $this;
    }

    /**
     * Gets with_signature_page
     *
     * @return bool|null
     */
    public function getWithSignaturePage()
    {
        return $this->container['with_signature_page'];
    }

    /**
     * Sets with_signature_page
     *
     * @param bool|null $with_signature_page When set to `true` the document will have a signature page added to the end, and all signers will be required to add their signature on that page.
     *
     * @return self
     */
    public function setWithSignaturePage($with_signature_page)
    {
        if (is_null($with_signature_page)) {
            throw new \InvalidArgumentException('non-nullable with_signature_page cannot be null');
        }
        $this->container['with_signature_page'] = $with_signature_page;

        return $this;
    }

    /**
     * Gets expires_in
     *
     * @return int|null
     */
    public function getExpiresIn()
    {
        return $this->container['expires_in'];
    }

    /**
     * Sets expires_in
     *
     * @param int|null $expires_in Number of days before the signature request expires. Defaults to the account expiration setting or template expiration (if the document is created from a template).
     *
     * @return self
     */
    public function setExpiresIn($expires_in)
    {
        if (is_null($expires_in)) {
            throw new \InvalidArgumentException('non-nullable expires_in cannot be null');
        }

        if (($expires_in < 1)) {
            throw new \InvalidArgumentException('invalid value for $expires_in when calling DocumentRequest., must be bigger than or equal to 1.');
        }

        $this->container['expires_in'] = $expires_in;

        return $this;
    }

    /**
     * Gets reminders
     *
     * @return bool|null
     */
    public function getReminders()
    {
        return $this->container['reminders'];
    }

    /**
     * Sets reminders
     *
     * @param bool|null $reminders Whether to send signing reminders to recipients. Reminders are sent on day 3, day 6, and day 10 if set to `true`. Defaults to `true`.
     *
     * @return self
     */
    public function setReminders($reminders)
    {
        if (is_null($reminders)) {
            throw new \InvalidArgumentException('non-nullable reminders cannot be null');
        }
        $this->container['reminders'] = $reminders;

        return $this;
    }

    /**
     * Gets apply_signing_order
     *
     * @return bool|null
     */
    public function getApplySigningOrder()
    {
        return $this->container['apply_signing_order'];
    }

    /**
     * Sets apply_signing_order
     *
     * @param bool|null $apply_signing_order When set to `true` recipients will sign one at a time in the order of the `recipients` collection of this request.
     *
     * @return self
     */
    public function setApplySigningOrder($apply_signing_order)
    {
        if (is_null($apply_signing_order)) {
            throw new \InvalidArgumentException('non-nullable apply_signing_order cannot be null');
        }
        $this->container['apply_signing_order'] = $apply_signing_order;

        return $this;
    }

    /**
     * Gets api_application_id
     *
     * @return string|null
     */
    public function getApiApplicationId()
    {
        return $this->container['api_application_id'];
    }

    /**
     * Sets api_application_id
     *
     * @param string|null $api_application_id Unique identifier for API Application settings to use. API Applications are optional and mainly used when isolating OAuth apps or for more control over embedded API settings
     *
     * @return self
     */
    public function setApiApplicationId($api_application_id)
    {
        if (is_null($api_application_id)) {
            throw new \InvalidArgumentException('non-nullable api_application_id cannot be null');
        }
        $this->container['api_application_id'] = $api_application_id;

        return $this;
    }

    /**
     * Gets embedded_signing
     *
     * @return bool|null
     */
    public function getEmbeddedSigning()
    {
        return $this->container['embedded_signing'];
    }

    /**
     * Sets embedded_signing
     *
     * @param bool|null $embedded_signing When set to `true` it enables embedded signing in your website/web application. Embedded functionality works with an iFrame and email authentication is disabled. :embedded_signinig defaults to `false`.
     *
     * @return self
     */
    public function setEmbeddedSigning($embedded_signing)
    {
        if (is_null($embedded_signing)) {
            throw new \InvalidArgumentException('non-nullable embedded_signing cannot be null');
        }
        $this->container['embedded_signing'] = $embedded_signing;

        return $this;
    }

    /**
     * Gets embedded_signing_notifications
     *
     * @return bool|null
     */
    public function getEmbeddedSigningNotifications()
    {
        return $this->container['embedded_signing_notifications'];
    }

    /**
     * Sets embedded_signing_notifications
     *
     * @param bool|null $embedded_signing_notifications On embedding signing, document owners (and CC'd contacts) do not get a notification email when documents have been completed. Setting this param to `true` will send out those final completed notifications. Default is `false`
     *
     * @return self
     */
    public function setEmbeddedSigningNotifications($embedded_signing_notifications)
    {
        if (is_null($embedded_signing_notifications)) {
            throw new \InvalidArgumentException('non-nullable embedded_signing_notifications cannot be null');
        }
        $this->container['embedded_signing_notifications'] = $embedded_signing_notifications;

        return $this;
    }

    /**
     * Gets text_tags
     *
     * @return bool|null
     */
    public function getTextTags()
    {
        return $this->container['text_tags'];
    }

    /**
     * Sets text_tags
     *
     * @param bool|null $text_tags An alternative way (if you can’t use the recommended way) of placing fields in specific locations of your document by using special text tags. Useful when changing the content of your files changes the location of fields. See API documentation for “Text Tags” for details. Defaults to false.
     *
     * @return self
     */
    public function setTextTags($text_tags)
    {
        if (is_null($text_tags)) {
            throw new \InvalidArgumentException('non-nullable text_tags cannot be null');
        }
        $this->container['text_tags'] = $text_tags;

        return $this;
    }

    /**
     * Gets custom_requester_name
     *
     * @return string|null
     */
    public function getCustomRequesterName()
    {
        return $this->container['custom_requester_name'];
    }

    /**
     * Sets custom_requester_name
     *
     * @param string|null $custom_requester_name Sets the custom requester name for the document. When set, this is the name used for all email communications, signing notifications, and in the audit file.
     *
     * @return self
     */
    public function setCustomRequesterName($custom_requester_name)
    {
        if (is_null($custom_requester_name)) {
            throw new \InvalidArgumentException('non-nullable custom_requester_name cannot be null');
        }
        $this->container['custom_requester_name'] = $custom_requester_name;

        return $this;
    }

    /**
     * Gets custom_requester_email
     *
     * @return string|null
     */
    public function getCustomRequesterEmail()
    {
        return $this->container['custom_requester_email'];
    }

    /**
     * Sets custom_requester_email
     *
     * @param string|null $custom_requester_email Sets the custom requester email for the document. When set, this is the email used for all email communications, signing notifications, and in the audit file.
     *
     * @return self
     */
    public function setCustomRequesterEmail($custom_requester_email)
    {
        if (is_null($custom_requester_email)) {
            throw new \InvalidArgumentException('non-nullable custom_requester_email cannot be null');
        }
        $this->container['custom_requester_email'] = $custom_requester_email;

        return $this;
    }

    /**
     * Gets redirect_url
     *
     * @return string|null
     */
    public function getRedirectUrl()
    {
        return $this->container['redirect_url'];
    }

    /**
     * Sets redirect_url
     *
     * @param string|null $redirect_url A URL that recipients are redirected to after successfully signing a document.
     *
     * @return self
     */
    public function setRedirectUrl($redirect_url)
    {
        if (is_null($redirect_url)) {
            throw new \InvalidArgumentException('non-nullable redirect_url cannot be null');
        }
        $this->container['redirect_url'] = $redirect_url;

        return $this;
    }

    /**
     * Gets allow_decline
     *
     * @return bool|null
     */
    public function getAllowDecline()
    {
        return $this->container['allow_decline'];
    }

    /**
     * Sets allow_decline
     *
     * @param bool|null $allow_decline Whether to allow recipients the option to decline signing a document. If multiple signers are involved in a document, any single recipient can cancel the entire document signing process by declining to sign.
     *
     * @return self
     */
    public function setAllowDecline($allow_decline)
    {
        if (is_null($allow_decline)) {
            throw new \InvalidArgumentException('non-nullable allow_decline cannot be null');
        }
        $this->container['allow_decline'] = $allow_decline;

        return $this;
    }

    /**
     * Gets allow_reassign
     *
     * @return bool|null
     */
    public function getAllowReassign()
    {
        return $this->container['allow_reassign'];
    }

    /**
     * Sets allow_reassign
     *
     * @param bool|null $allow_reassign In some cases a signer is not the right person to sign and may need to reassign their signing responsibilities to another person. This feature allows them to reassign the document to someone else.
     *
     * @return self
     */
    public function setAllowReassign($allow_reassign)
    {
        if (is_null($allow_reassign)) {
            throw new \InvalidArgumentException('non-nullable allow_reassign cannot be null');
        }
        $this->container['allow_reassign'] = $allow_reassign;

        return $this;
    }

    /**
     * Gets decline_redirect_url
     *
     * @return string|null
     */
    public function getDeclineRedirectUrl()
    {
        return $this->container['decline_redirect_url'];
    }

    /**
     * Sets decline_redirect_url
     *
     * @param string|null $decline_redirect_url A URL that recipients are redirected to if the document is declined.
     *
     * @return self
     */
    public function setDeclineRedirectUrl($decline_redirect_url)
    {
        if (is_null($decline_redirect_url)) {
            throw new \InvalidArgumentException('non-nullable decline_redirect_url cannot be null');
        }
        $this->container['decline_redirect_url'] = $decline_redirect_url;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language Sets the language for all recipients on the document and updates all recipient side interactions including the document email and the document itself. Accepted languages: English, Français, Español, Deutsch, Polski, Português, Dansk, Nederlands, Italiano, Русский, Svenska, العربية, Ελληνικά, Türkçe, Slovenčina. Defaults to English. Language should be sent in ISO 639-1 format: en, fr, es, de, pl, pt, da, nl, it, ru, sv, ar, el, tr, sk.
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata Optional key-value data that can be associated with the document. If set, will be available every time the document data is returned.
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            throw new \InvalidArgumentException('non-nullable metadata cannot be null');
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return \SignWell\Sdk\Models\FieldsInnerInner[][]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param \SignWell\Sdk\Models\FieldsInnerInner[][]|null $fields Document fields placed on a document for collecting data or signatures from recipients. At least one field must be present in the Create Document request if `draft` is `false` (unless adding a signature page by using `with_signature_page`). Field data should be sent as a 2-dimensional JSON array. One array of fields is needed for each file in the files array. An array of fields can be empty if you have a file that does not contain any fields.
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            throw new \InvalidArgumentException('non-nullable fields cannot be null');
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets attachment_requests
     *
     * @return \SignWell\Sdk\Models\AttachmentRequestsInner[]|null
     */
    public function getAttachmentRequests()
    {
        return $this->container['attachment_requests'];
    }

    /**
     * Sets attachment_requests
     *
     * @param \SignWell\Sdk\Models\AttachmentRequestsInner[]|null $attachment_requests Attachments that a recipient must upload to complete the signing process. Attachment requests are shown after all document fields have been completed.
     *
     * @return self
     */
    public function setAttachmentRequests($attachment_requests)
    {
        if (is_null($attachment_requests)) {
            throw new \InvalidArgumentException('non-nullable attachment_requests cannot be null');
        }
        $this->container['attachment_requests'] = $attachment_requests;

        return $this;
    }

    /**
     * Gets copied_contacts
     *
     * @return \SignWell\Sdk\Models\CopiedContactsInner[]|null
     */
    public function getCopiedContacts()
    {
        return $this->container['copied_contacts'];
    }

    /**
     * Sets copied_contacts
     *
     * @param \SignWell\Sdk\Models\CopiedContactsInner[]|null $copied_contacts Copied contacts are emailed the final document once it has been completed by all recipients.
     *
     * @return self
     */
    public function setCopiedContacts($copied_contacts)
    {
        if (is_null($copied_contacts)) {
            throw new \InvalidArgumentException('non-nullable copied_contacts cannot be null');
        }
        $this->container['copied_contacts'] = $copied_contacts;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \SignWell\Sdk\Models\LabelRequest[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \SignWell\Sdk\Models\LabelRequest[]|null $labels Labels can be used to organize documents in a way that can make it easy to find using the document search in SignWell. A document can have multiple labels.
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets checkbox_groups
     *
     * @return \SignWell\Sdk\Models\CheckboxGroupsInner[]|null
     */
    public function getCheckboxGroups()
    {
        return $this->container['checkbox_groups'];
    }

    /**
     * Sets checkbox_groups
     *
     * @param \SignWell\Sdk\Models\CheckboxGroupsInner[]|null $checkbox_groups Checkbox fields that are placed on a document can be grouped with selection requirements. At least 2 checkbox fields in an array of fields must be assigned to the same recipient.
     *
     * @return self
     */
    public function setCheckboxGroups($checkbox_groups)
    {
        if (is_null($checkbox_groups)) {
            throw new \InvalidArgumentException('non-nullable checkbox_groups cannot be null');
        }
        $this->container['checkbox_groups'] = $checkbox_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
