<?php

declare(strict_types=1);
/**
 * DocumentFromTemplateResponse
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * DocumentFromTemplateResponse Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentFromTemplateResponse implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentFromTemplateResponse';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'test_mode' => 'bool',
        'id' => 'string',
        'template_id' => 'string',
        'template_ids' => 'string[]',
        'api_application_id' => 'string',
        'requester_email_address' => 'string',
        'custom_requester_name' => 'string',
        'custom_requester_email' => 'string',
        'name' => 'string',
        'subject' => 'string',
        'message' => 'string',
        'metadata' => 'array<string,string>',
        'created_at' => '\DateTime',
        'updated_at' => '\DateTime',
        'recipients' => '\SignWell\Sdk\Models\DocumentFromTemplateResponseRecipientsInner[]',
        'status' => 'string',
        'reminders' => 'bool',
        'archived' => 'bool',
        'embedded_signing' => 'bool',
        'embedded_edit_url' => 'string',
        'embedded_preview_url' => 'string',
        'apply_signing_order' => 'bool',
        'redirect_url' => 'string',
        'decline_redirect_url' => 'string',
        'language' => 'string',
        'expires_in' => 'int',
        'decline_message' => 'string',
        'error_message' => 'string',
        'embedded_signing_notifications' => 'bool',
        'attachment_requests' => '\SignWell\Sdk\Models\DocumentResponseAttachmentRequestsInner[]',
        'files' => '\SignWell\Sdk\Models\FileInfo[]',
        'copied_contacts' => '\SignWell\Sdk\Models\CopiedContactInfo[]',
        'fields' => '\SignWell\Sdk\Models\DocumentFromTemplateResponseFieldsInnerInner[][]',
        'allow_decline' => 'bool',
        'allow_reassign' => 'bool',
        'labels' => '\SignWell\Sdk\Models\LabelInfo[]',
        'checkbox_groups' => '\SignWell\Sdk\Models\CheckboxGroupInfo[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'test_mode' => null,
        'id' => null,
        'template_id' => null,
        'template_ids' => null,
        'api_application_id' => 'uuid',
        'requester_email_address' => 'email',
        'custom_requester_name' => null,
        'custom_requester_email' => 'email',
        'name' => null,
        'subject' => null,
        'message' => null,
        'metadata' => null,
        'created_at' => 'date-time',
        'updated_at' => 'date-time',
        'recipients' => null,
        'status' => null,
        'reminders' => null,
        'archived' => null,
        'embedded_signing' => null,
        'embedded_edit_url' => 'url',
        'embedded_preview_url' => 'url',
        'apply_signing_order' => null,
        'redirect_url' => 'url',
        'decline_redirect_url' => 'url',
        'language' => null,
        'expires_in' => null,
        'decline_message' => null,
        'error_message' => null,
        'embedded_signing_notifications' => null,
        'attachment_requests' => null,
        'files' => null,
        'copied_contacts' => null,
        'fields' => null,
        'allow_decline' => null,
        'allow_reassign' => null,
        'labels' => null,
        'checkbox_groups' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'test_mode' => false,
        'id' => false,
        'template_id' => false,
        'template_ids' => false,
        'api_application_id' => true,
        'requester_email_address' => false,
        'custom_requester_name' => true,
        'custom_requester_email' => true,
        'name' => false,
        'subject' => false,
        'message' => false,
        'metadata' => true,
        'created_at' => false,
        'updated_at' => false,
        'recipients' => false,
        'status' => false,
        'reminders' => false,
        'archived' => false,
        'embedded_signing' => false,
        'embedded_edit_url' => false,
        'embedded_preview_url' => true,
        'apply_signing_order' => false,
        'redirect_url' => true,
        'decline_redirect_url' => true,
        'language' => false,
        'expires_in' => false,
        'decline_message' => true,
        'error_message' => true,
        'embedded_signing_notifications' => false,
        'attachment_requests' => false,
        'files' => false,
        'copied_contacts' => false,
        'fields' => false,
        'allow_decline' => true,
        'allow_reassign' => true,
        'labels' => false,
        'checkbox_groups' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'test_mode' => 'test_mode',
        'id' => 'id',
        'template_id' => 'template_id',
        'template_ids' => 'template_ids',
        'api_application_id' => 'api_application_id',
        'requester_email_address' => 'requester_email_address',
        'custom_requester_name' => 'custom_requester_name',
        'custom_requester_email' => 'custom_requester_email',
        'name' => 'name',
        'subject' => 'subject',
        'message' => 'message',
        'metadata' => 'metadata',
        'created_at' => 'created_at',
        'updated_at' => 'updated_at',
        'recipients' => 'recipients',
        'status' => 'status',
        'reminders' => 'reminders',
        'archived' => 'archived',
        'embedded_signing' => 'embedded_signing',
        'embedded_edit_url' => 'embedded_edit_url',
        'embedded_preview_url' => 'embedded_preview_url',
        'apply_signing_order' => 'apply_signing_order',
        'redirect_url' => 'redirect_url',
        'decline_redirect_url' => 'decline_redirect_url',
        'language' => 'language',
        'expires_in' => 'expires_in',
        'decline_message' => 'decline_message',
        'error_message' => 'error_message',
        'embedded_signing_notifications' => 'embedded_signing_notifications',
        'attachment_requests' => 'attachment_requests',
        'files' => 'files',
        'copied_contacts' => 'copied_contacts',
        'fields' => 'fields',
        'allow_decline' => 'allow_decline',
        'allow_reassign' => 'allow_reassign',
        'labels' => 'labels',
        'checkbox_groups' => 'checkbox_groups'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'test_mode' => 'setTestMode',
        'id' => 'setId',
        'template_id' => 'setTemplateId',
        'template_ids' => 'setTemplateIds',
        'api_application_id' => 'setApiApplicationId',
        'requester_email_address' => 'setRequesterEmailAddress',
        'custom_requester_name' => 'setCustomRequesterName',
        'custom_requester_email' => 'setCustomRequesterEmail',
        'name' => 'setName',
        'subject' => 'setSubject',
        'message' => 'setMessage',
        'metadata' => 'setMetadata',
        'created_at' => 'setCreatedAt',
        'updated_at' => 'setUpdatedAt',
        'recipients' => 'setRecipients',
        'status' => 'setStatus',
        'reminders' => 'setReminders',
        'archived' => 'setArchived',
        'embedded_signing' => 'setEmbeddedSigning',
        'embedded_edit_url' => 'setEmbeddedEditUrl',
        'embedded_preview_url' => 'setEmbeddedPreviewUrl',
        'apply_signing_order' => 'setApplySigningOrder',
        'redirect_url' => 'setRedirectUrl',
        'decline_redirect_url' => 'setDeclineRedirectUrl',
        'language' => 'setLanguage',
        'expires_in' => 'setExpiresIn',
        'decline_message' => 'setDeclineMessage',
        'error_message' => 'setErrorMessage',
        'embedded_signing_notifications' => 'setEmbeddedSigningNotifications',
        'attachment_requests' => 'setAttachmentRequests',
        'files' => 'setFiles',
        'copied_contacts' => 'setCopiedContacts',
        'fields' => 'setFields',
        'allow_decline' => 'setAllowDecline',
        'allow_reassign' => 'setAllowReassign',
        'labels' => 'setLabels',
        'checkbox_groups' => 'setCheckboxGroups'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'test_mode' => 'getTestMode',
        'id' => 'getId',
        'template_id' => 'getTemplateId',
        'template_ids' => 'getTemplateIds',
        'api_application_id' => 'getApiApplicationId',
        'requester_email_address' => 'getRequesterEmailAddress',
        'custom_requester_name' => 'getCustomRequesterName',
        'custom_requester_email' => 'getCustomRequesterEmail',
        'name' => 'getName',
        'subject' => 'getSubject',
        'message' => 'getMessage',
        'metadata' => 'getMetadata',
        'created_at' => 'getCreatedAt',
        'updated_at' => 'getUpdatedAt',
        'recipients' => 'getRecipients',
        'status' => 'getStatus',
        'reminders' => 'getReminders',
        'archived' => 'getArchived',
        'embedded_signing' => 'getEmbeddedSigning',
        'embedded_edit_url' => 'getEmbeddedEditUrl',
        'embedded_preview_url' => 'getEmbeddedPreviewUrl',
        'apply_signing_order' => 'getApplySigningOrder',
        'redirect_url' => 'getRedirectUrl',
        'decline_redirect_url' => 'getDeclineRedirectUrl',
        'language' => 'getLanguage',
        'expires_in' => 'getExpiresIn',
        'decline_message' => 'getDeclineMessage',
        'error_message' => 'getErrorMessage',
        'embedded_signing_notifications' => 'getEmbeddedSigningNotifications',
        'attachment_requests' => 'getAttachmentRequests',
        'files' => 'getFiles',
        'copied_contacts' => 'getCopiedContacts',
        'fields' => 'getFields',
        'allow_decline' => 'getAllowDecline',
        'allow_reassign' => 'getAllowReassign',
        'labels' => 'getLabels',
        'checkbox_groups' => 'getCheckboxGroups'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(?array $data = null)
    {
        $this->setIfExists('test_mode', $data ?? [], null);
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('template_id', $data ?? [], null);
        $this->setIfExists('template_ids', $data ?? [], null);
        $this->setIfExists('api_application_id', $data ?? [], null);
        $this->setIfExists('requester_email_address', $data ?? [], null);
        $this->setIfExists('custom_requester_name', $data ?? [], null);
        $this->setIfExists('custom_requester_email', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('metadata', $data ?? [], null);
        $this->setIfExists('created_at', $data ?? [], null);
        $this->setIfExists('updated_at', $data ?? [], null);
        $this->setIfExists('recipients', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('reminders', $data ?? [], null);
        $this->setIfExists('archived', $data ?? [], null);
        $this->setIfExists('embedded_signing', $data ?? [], null);
        $this->setIfExists('embedded_edit_url', $data ?? [], null);
        $this->setIfExists('embedded_preview_url', $data ?? [], null);
        $this->setIfExists('apply_signing_order', $data ?? [], null);
        $this->setIfExists('redirect_url', $data ?? [], null);
        $this->setIfExists('decline_redirect_url', $data ?? [], null);
        $this->setIfExists('language', $data ?? [], null);
        $this->setIfExists('expires_in', $data ?? [], null);
        $this->setIfExists('decline_message', $data ?? [], null);
        $this->setIfExists('error_message', $data ?? [], null);
        $this->setIfExists('embedded_signing_notifications', $data ?? [], null);
        $this->setIfExists('attachment_requests', $data ?? [], null);
        $this->setIfExists('files', $data ?? [], null);
        $this->setIfExists('copied_contacts', $data ?? [], null);
        $this->setIfExists('fields', $data ?? [], null);
        $this->setIfExists('allow_decline', $data ?? [], null);
        $this->setIfExists('allow_reassign', $data ?? [], null);
        $this->setIfExists('labels', $data ?? [], null);
        $this->setIfExists('checkbox_groups', $data ?? [], null);
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['test_mode'] === null) {
            $invalidProperties[] = "'test_mode' can't be null";
        }
        if ($this->container['id'] === null) {
            $invalidProperties[] = "'id' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets test_mode
     *
     * @return bool
     */
    public function getTestMode()
    {
        return $this->container['test_mode'];
    }

    /**
     * Sets test_mode
     *
     * @param bool $test_mode test_mode
     *
     * @return self
     */
    public function setTestMode($test_mode)
    {
        if (is_null($test_mode)) {
            throw new \InvalidArgumentException('non-nullable test_mode cannot be null');
        }
        $this->container['test_mode'] = $test_mode;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets template_id
     *
     * @return string|null
     */
    public function getTemplateId()
    {
        return $this->container['template_id'];
    }

    /**
     * Sets template_id
     *
     * @param string|null $template_id template_id
     *
     * @return self
     */
    public function setTemplateId($template_id)
    {
        if (is_null($template_id)) {
            throw new \InvalidArgumentException('non-nullable template_id cannot be null');
        }
        $this->container['template_id'] = $template_id;

        return $this;
    }

    /**
     * Gets template_ids
     *
     * @return string[]|null
     */
    public function getTemplateIds()
    {
        return $this->container['template_ids'];
    }

    /**
     * Sets template_ids
     *
     * @param string[]|null $template_ids template_ids
     *
     * @return self
     */
    public function setTemplateIds($template_ids)
    {
        if (is_null($template_ids)) {
            throw new \InvalidArgumentException('non-nullable template_ids cannot be null');
        }
        $this->container['template_ids'] = $template_ids;

        return $this;
    }

    /**
     * Gets api_application_id
     *
     * @return string|null
     */
    public function getApiApplicationId()
    {
        return $this->container['api_application_id'];
    }

    /**
     * Sets api_application_id
     *
     * @param string|null $api_application_id api_application_id
     *
     * @return self
     */
    public function setApiApplicationId($api_application_id)
    {
        if (is_null($api_application_id)) {
            array_push($this->openAPINullablesSetToNull, 'api_application_id');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('api_application_id', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['api_application_id'] = $api_application_id;

        return $this;
    }

    /**
     * Gets requester_email_address
     *
     * @return string|null
     */
    public function getRequesterEmailAddress()
    {
        return $this->container['requester_email_address'];
    }

    /**
     * Sets requester_email_address
     *
     * @param string|null $requester_email_address requester_email_address
     *
     * @return self
     */
    public function setRequesterEmailAddress($requester_email_address)
    {
        if (is_null($requester_email_address)) {
            throw new \InvalidArgumentException('non-nullable requester_email_address cannot be null');
        }
        $this->container['requester_email_address'] = $requester_email_address;

        return $this;
    }

    /**
     * Gets custom_requester_name
     *
     * @return string|null
     */
    public function getCustomRequesterName()
    {
        return $this->container['custom_requester_name'];
    }

    /**
     * Sets custom_requester_name
     *
     * @param string|null $custom_requester_name custom_requester_name
     *
     * @return self
     */
    public function setCustomRequesterName($custom_requester_name)
    {
        if (is_null($custom_requester_name)) {
            array_push($this->openAPINullablesSetToNull, 'custom_requester_name');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_requester_name', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_requester_name'] = $custom_requester_name;

        return $this;
    }

    /**
     * Gets custom_requester_email
     *
     * @return string|null
     */
    public function getCustomRequesterEmail()
    {
        return $this->container['custom_requester_email'];
    }

    /**
     * Sets custom_requester_email
     *
     * @param string|null $custom_requester_email custom_requester_email
     *
     * @return self
     */
    public function setCustomRequesterEmail($custom_requester_email)
    {
        if (is_null($custom_requester_email)) {
            array_push($this->openAPINullablesSetToNull, 'custom_requester_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('custom_requester_email', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['custom_requester_email'] = $custom_requester_email;

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            throw new \InvalidArgumentException('non-nullable subject cannot be null');
        }
        $this->container['subject'] = $subject;

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            throw new \InvalidArgumentException('non-nullable message cannot be null');
        }
        $this->container['message'] = $message;

        return $this;
    }

    /**
     * Gets metadata
     *
     * @return array<string,string>|null
     */
    public function getMetadata()
    {
        return $this->container['metadata'];
    }

    /**
     * Sets metadata
     *
     * @param array<string,string>|null $metadata metadata
     *
     * @return self
     */
    public function setMetadata($metadata)
    {
        if (is_null($metadata)) {
            array_push($this->openAPINullablesSetToNull, 'metadata');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('metadata', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['metadata'] = $metadata;

        return $this;
    }

    /**
     * Gets created_at
     *
     * @return \DateTime|null
     */
    public function getCreatedAt()
    {
        return $this->container['created_at'];
    }

    /**
     * Sets created_at
     *
     * @param \DateTime|null $created_at created_at
     *
     * @return self
     */
    public function setCreatedAt($created_at)
    {
        if (is_null($created_at)) {
            throw new \InvalidArgumentException('non-nullable created_at cannot be null');
        }
        $this->container['created_at'] = $created_at;

        return $this;
    }

    /**
     * Gets updated_at
     *
     * @return \DateTime|null
     */
    public function getUpdatedAt()
    {
        return $this->container['updated_at'];
    }

    /**
     * Sets updated_at
     *
     * @param \DateTime|null $updated_at updated_at
     *
     * @return self
     */
    public function setUpdatedAt($updated_at)
    {
        if (is_null($updated_at)) {
            throw new \InvalidArgumentException('non-nullable updated_at cannot be null');
        }
        $this->container['updated_at'] = $updated_at;

        return $this;
    }

    /**
     * Gets recipients
     *
     * @return \SignWell\Sdk\Models\DocumentFromTemplateResponseRecipientsInner[]|null
     */
    public function getRecipients()
    {
        return $this->container['recipients'];
    }

    /**
     * Sets recipients
     *
     * @param \SignWell\Sdk\Models\DocumentFromTemplateResponseRecipientsInner[]|null $recipients recipients
     *
     * @return self
     */
    public function setRecipients($recipients)
    {
        if (is_null($recipients)) {
            throw new \InvalidArgumentException('non-nullable recipients cannot be null');
        }
        $this->container['recipients'] = $recipients;

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status Possible values: Draft, Created, Sending, Sent, Pending, Viewed, Completed, Manually completed, Declined, Canceled, Bounced, Blocked, Error, Expired
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;

        return $this;
    }

    /**
     * Gets reminders
     *
     * @return bool|null
     */
    public function getReminders()
    {
        return $this->container['reminders'];
    }

    /**
     * Sets reminders
     *
     * @param bool|null $reminders reminders
     *
     * @return self
     */
    public function setReminders($reminders)
    {
        if (is_null($reminders)) {
            throw new \InvalidArgumentException('non-nullable reminders cannot be null');
        }
        $this->container['reminders'] = $reminders;

        return $this;
    }

    /**
     * Gets archived
     *
     * @return bool|null
     */
    public function getArchived()
    {
        return $this->container['archived'];
    }

    /**
     * Sets archived
     *
     * @param bool|null $archived archived
     *
     * @return self
     */
    public function setArchived($archived)
    {
        if (is_null($archived)) {
            throw new \InvalidArgumentException('non-nullable archived cannot be null');
        }
        $this->container['archived'] = $archived;

        return $this;
    }

    /**
     * Gets embedded_signing
     *
     * @return bool|null
     */
    public function getEmbeddedSigning()
    {
        return $this->container['embedded_signing'];
    }

    /**
     * Sets embedded_signing
     *
     * @param bool|null $embedded_signing embedded_signing
     *
     * @return self
     */
    public function setEmbeddedSigning($embedded_signing)
    {
        if (is_null($embedded_signing)) {
            throw new \InvalidArgumentException('non-nullable embedded_signing cannot be null');
        }
        $this->container['embedded_signing'] = $embedded_signing;

        return $this;
    }

    /**
     * Gets embedded_edit_url
     *
     * @return string|null
     */
    public function getEmbeddedEditUrl()
    {
        return $this->container['embedded_edit_url'];
    }

    /**
     * Sets embedded_edit_url
     *
     * @param string|null $embedded_edit_url embedded_edit_url
     *
     * @return self
     */
    public function setEmbeddedEditUrl($embedded_edit_url)
    {
        if (is_null($embedded_edit_url)) {
            throw new \InvalidArgumentException('non-nullable embedded_edit_url cannot be null');
        }
        $this->container['embedded_edit_url'] = $embedded_edit_url;

        return $this;
    }

    /**
     * Gets embedded_preview_url
     *
     * @return string|null
     */
    public function getEmbeddedPreviewUrl()
    {
        return $this->container['embedded_preview_url'];
    }

    /**
     * Sets embedded_preview_url
     *
     * @param string|null $embedded_preview_url embedded_preview_url
     *
     * @return self
     */
    public function setEmbeddedPreviewUrl($embedded_preview_url)
    {
        if (is_null($embedded_preview_url)) {
            array_push($this->openAPINullablesSetToNull, 'embedded_preview_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('embedded_preview_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['embedded_preview_url'] = $embedded_preview_url;

        return $this;
    }

    /**
     * Gets apply_signing_order
     *
     * @return bool|null
     */
    public function getApplySigningOrder()
    {
        return $this->container['apply_signing_order'];
    }

    /**
     * Sets apply_signing_order
     *
     * @param bool|null $apply_signing_order apply_signing_order
     *
     * @return self
     */
    public function setApplySigningOrder($apply_signing_order)
    {
        if (is_null($apply_signing_order)) {
            throw new \InvalidArgumentException('non-nullable apply_signing_order cannot be null');
        }
        $this->container['apply_signing_order'] = $apply_signing_order;

        return $this;
    }

    /**
     * Gets redirect_url
     *
     * @return string|null
     */
    public function getRedirectUrl()
    {
        return $this->container['redirect_url'];
    }

    /**
     * Sets redirect_url
     *
     * @param string|null $redirect_url redirect_url
     *
     * @return self
     */
    public function setRedirectUrl($redirect_url)
    {
        if (is_null($redirect_url)) {
            array_push($this->openAPINullablesSetToNull, 'redirect_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('redirect_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['redirect_url'] = $redirect_url;

        return $this;
    }

    /**
     * Gets decline_redirect_url
     *
     * @return string|null
     */
    public function getDeclineRedirectUrl()
    {
        return $this->container['decline_redirect_url'];
    }

    /**
     * Sets decline_redirect_url
     *
     * @param string|null $decline_redirect_url decline_redirect_url
     *
     * @return self
     */
    public function setDeclineRedirectUrl($decline_redirect_url)
    {
        if (is_null($decline_redirect_url)) {
            array_push($this->openAPINullablesSetToNull, 'decline_redirect_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('decline_redirect_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['decline_redirect_url'] = $decline_redirect_url;

        return $this;
    }

    /**
     * Gets language
     *
     * @return string|null
     */
    public function getLanguage()
    {
        return $this->container['language'];
    }

    /**
     * Sets language
     *
     * @param string|null $language language
     *
     * @return self
     */
    public function setLanguage($language)
    {
        if (is_null($language)) {
            throw new \InvalidArgumentException('non-nullable language cannot be null');
        }
        $this->container['language'] = $language;

        return $this;
    }

    /**
     * Gets expires_in
     *
     * @return int|null
     */
    public function getExpiresIn()
    {
        return $this->container['expires_in'];
    }

    /**
     * Sets expires_in
     *
     * @param int|null $expires_in expires_in
     *
     * @return self
     */
    public function setExpiresIn($expires_in)
    {
        if (is_null($expires_in)) {
            throw new \InvalidArgumentException('non-nullable expires_in cannot be null');
        }
        $this->container['expires_in'] = $expires_in;

        return $this;
    }

    /**
     * Gets decline_message
     *
     * @return string|null
     */
    public function getDeclineMessage()
    {
        return $this->container['decline_message'];
    }

    /**
     * Sets decline_message
     *
     * @param string|null $decline_message decline_message
     *
     * @return self
     */
    public function setDeclineMessage($decline_message)
    {
        if (is_null($decline_message)) {
            array_push($this->openAPINullablesSetToNull, 'decline_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('decline_message', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['decline_message'] = $decline_message;

        return $this;
    }

    /**
     * Gets error_message
     *
     * @return string|null
     */
    public function getErrorMessage()
    {
        return $this->container['error_message'];
    }

    /**
     * Sets error_message
     *
     * @param string|null $error_message error_message
     *
     * @return self
     */
    public function setErrorMessage($error_message)
    {
        if (is_null($error_message)) {
            array_push($this->openAPINullablesSetToNull, 'error_message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('error_message', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['error_message'] = $error_message;

        return $this;
    }

    /**
     * Gets embedded_signing_notifications
     *
     * @return bool|null
     */
    public function getEmbeddedSigningNotifications()
    {
        return $this->container['embedded_signing_notifications'];
    }

    /**
     * Sets embedded_signing_notifications
     *
     * @param bool|null $embedded_signing_notifications embedded_signing_notifications
     *
     * @return self
     */
    public function setEmbeddedSigningNotifications($embedded_signing_notifications)
    {
        if (is_null($embedded_signing_notifications)) {
            throw new \InvalidArgumentException('non-nullable embedded_signing_notifications cannot be null');
        }
        $this->container['embedded_signing_notifications'] = $embedded_signing_notifications;

        return $this;
    }

    /**
     * Gets attachment_requests
     *
     * @return \SignWell\Sdk\Models\DocumentResponseAttachmentRequestsInner[]|null
     */
    public function getAttachmentRequests()
    {
        return $this->container['attachment_requests'];
    }

    /**
     * Sets attachment_requests
     *
     * @param \SignWell\Sdk\Models\DocumentResponseAttachmentRequestsInner[]|null $attachment_requests attachment_requests
     *
     * @return self
     */
    public function setAttachmentRequests($attachment_requests)
    {
        if (is_null($attachment_requests)) {
            throw new \InvalidArgumentException('non-nullable attachment_requests cannot be null');
        }
        $this->container['attachment_requests'] = $attachment_requests;

        return $this;
    }

    /**
     * Gets files
     *
     * @return \SignWell\Sdk\Models\FileInfo[]|null
     */
    public function getFiles()
    {
        return $this->container['files'];
    }

    /**
     * Sets files
     *
     * @param \SignWell\Sdk\Models\FileInfo[]|null $files files
     *
     * @return self
     */
    public function setFiles($files)
    {
        if (is_null($files)) {
            throw new \InvalidArgumentException('non-nullable files cannot be null');
        }
        $this->container['files'] = $files;

        return $this;
    }

    /**
     * Gets copied_contacts
     *
     * @return \SignWell\Sdk\Models\CopiedContactInfo[]|null
     */
    public function getCopiedContacts()
    {
        return $this->container['copied_contacts'];
    }

    /**
     * Sets copied_contacts
     *
     * @param \SignWell\Sdk\Models\CopiedContactInfo[]|null $copied_contacts copied_contacts
     *
     * @return self
     */
    public function setCopiedContacts($copied_contacts)
    {
        if (is_null($copied_contacts)) {
            throw new \InvalidArgumentException('non-nullable copied_contacts cannot be null');
        }
        $this->container['copied_contacts'] = $copied_contacts;

        return $this;
    }

    /**
     * Gets fields
     *
     * @return \SignWell\Sdk\Models\DocumentFromTemplateResponseFieldsInnerInner[][]|null
     */
    public function getFields()
    {
        return $this->container['fields'];
    }

    /**
     * Sets fields
     *
     * @param \SignWell\Sdk\Models\DocumentFromTemplateResponseFieldsInnerInner[][]|null $fields fields
     *
     * @return self
     */
    public function setFields($fields)
    {
        if (is_null($fields)) {
            throw new \InvalidArgumentException('non-nullable fields cannot be null');
        }
        $this->container['fields'] = $fields;

        return $this;
    }

    /**
     * Gets allow_decline
     *
     * @return bool|null
     */
    public function getAllowDecline()
    {
        return $this->container['allow_decline'];
    }

    /**
     * Sets allow_decline
     *
     * @param bool|null $allow_decline allow_decline
     *
     * @return self
     */
    public function setAllowDecline($allow_decline)
    {
        if (is_null($allow_decline)) {
            array_push($this->openAPINullablesSetToNull, 'allow_decline');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allow_decline', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allow_decline'] = $allow_decline;

        return $this;
    }

    /**
     * Gets allow_reassign
     *
     * @return bool|null
     */
    public function getAllowReassign()
    {
        return $this->container['allow_reassign'];
    }

    /**
     * Sets allow_reassign
     *
     * @param bool|null $allow_reassign allow_reassign
     *
     * @return self
     */
    public function setAllowReassign($allow_reassign)
    {
        if (is_null($allow_reassign)) {
            array_push($this->openAPINullablesSetToNull, 'allow_reassign');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('allow_reassign', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['allow_reassign'] = $allow_reassign;

        return $this;
    }

    /**
     * Gets labels
     *
     * @return \SignWell\Sdk\Models\LabelInfo[]|null
     */
    public function getLabels()
    {
        return $this->container['labels'];
    }

    /**
     * Sets labels
     *
     * @param \SignWell\Sdk\Models\LabelInfo[]|null $labels labels
     *
     * @return self
     */
    public function setLabels($labels)
    {
        if (is_null($labels)) {
            throw new \InvalidArgumentException('non-nullable labels cannot be null');
        }
        $this->container['labels'] = $labels;

        return $this;
    }

    /**
     * Gets checkbox_groups
     *
     * @return \SignWell\Sdk\Models\CheckboxGroupInfo[]|null
     */
    public function getCheckboxGroups()
    {
        return $this->container['checkbox_groups'];
    }

    /**
     * Sets checkbox_groups
     *
     * @param \SignWell\Sdk\Models\CheckboxGroupInfo[]|null $checkbox_groups checkbox_groups
     *
     * @return self
     */
    public function setCheckboxGroups($checkbox_groups)
    {
        if (is_null($checkbox_groups)) {
            throw new \InvalidArgumentException('non-nullable checkbox_groups cannot be null');
        }
        $this->container['checkbox_groups'] = $checkbox_groups;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
