<?php

declare(strict_types=1);
/**
 * DocumentFromTemplateResponseRecipientsInner
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * DocumentFromTemplateResponseRecipientsInner Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class DocumentFromTemplateResponseRecipientsInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'DocumentFromTemplateResponse_recipients_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'name' => 'string',
        'email' => 'string',
        'role' => 'string',
        'message' => 'string',
        'subject' => 'string',
        'send_email' => 'bool',
        'send_email_delay' => 'int',
        'signing_order' => 'int',
        'signing_url' => 'string',
        'embedded_signing_url' => 'string',
        'bounced' => 'bool',
        'bounced_details' => 'string',
        'attachment_requests' => '\SignWell\Sdk\Models\AttachmentRequestInfo[]',
        'passcode' => 'string',
        'status' => 'string',
        'placeholder_name' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'name' => null,
        'email' => null,
        'role' => null,
        'message' => null,
        'subject' => null,
        'send_email' => null,
        'send_email_delay' => null,
        'signing_order' => null,
        'signing_url' => 'url',
        'embedded_signing_url' => 'url',
        'bounced' => null,
        'bounced_details' => null,
        'attachment_requests' => null,
        'passcode' => null,
        'status' => null,
        'placeholder_name' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'id' => false,
        'name' => false,
        'email' => false,
        'role' => false,
        'message' => true,
        'subject' => true,
        'send_email' => true,
        'send_email_delay' => true,
        'signing_order' => false,
        'signing_url' => true,
        'embedded_signing_url' => true,
        'bounced' => true,
        'bounced_details' => true,
        'attachment_requests' => false,
        'passcode' => true,
        'status' => false,
        'placeholder_name' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'name' => 'name',
        'email' => 'email',
        'role' => 'role',
        'message' => 'message',
        'subject' => 'subject',
        'send_email' => 'send_email',
        'send_email_delay' => 'send_email_delay',
        'signing_order' => 'signing_order',
        'signing_url' => 'signing_url',
        'embedded_signing_url' => 'embedded_signing_url',
        'bounced' => 'bounced',
        'bounced_details' => 'bounced_details',
        'attachment_requests' => 'attachment_requests',
        'passcode' => 'passcode',
        'status' => 'status',
        'placeholder_name' => 'placeholder_name'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'name' => 'setName',
        'email' => 'setEmail',
        'role' => 'setRole',
        'message' => 'setMessage',
        'subject' => 'setSubject',
        'send_email' => 'setSendEmail',
        'send_email_delay' => 'setSendEmailDelay',
        'signing_order' => 'setSigningOrder',
        'signing_url' => 'setSigningUrl',
        'embedded_signing_url' => 'setEmbeddedSigningUrl',
        'bounced' => 'setBounced',
        'bounced_details' => 'setBouncedDetails',
        'attachment_requests' => 'setAttachmentRequests',
        'passcode' => 'setPasscode',
        'status' => 'setStatus',
        'placeholder_name' => 'setPlaceholderName'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'name' => 'getName',
        'email' => 'getEmail',
        'role' => 'getRole',
        'message' => 'getMessage',
        'subject' => 'getSubject',
        'send_email' => 'getSendEmail',
        'send_email_delay' => 'getSendEmailDelay',
        'signing_order' => 'getSigningOrder',
        'signing_url' => 'getSigningUrl',
        'embedded_signing_url' => 'getEmbeddedSigningUrl',
        'bounced' => 'getBounced',
        'bounced_details' => 'getBouncedDetails',
        'attachment_requests' => 'getAttachmentRequests',
        'passcode' => 'getPasscode',
        'status' => 'getStatus',
        'placeholder_name' => 'getPlaceholderName'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];


    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->setIfExists('id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('email', $data ?? [], null);
        $this->setIfExists('role', $data ?? [], null);
        $this->setIfExists('message', $data ?? [], null);
        $this->setIfExists('subject', $data ?? [], null);
        $this->setIfExists('send_email', $data ?? [], null);
        $this->setIfExists('send_email_delay', $data ?? [], null);
        $this->setIfExists('signing_order', $data ?? [], null);
        $this->setIfExists('signing_url', $data ?? [], null);
        $this->setIfExists('embedded_signing_url', $data ?? [], null);
        $this->setIfExists('bounced', $data ?? [], null);
        $this->setIfExists('bounced_details', $data ?? [], null);
        $this->setIfExists('attachment_requests', $data ?? [], null);
        $this->setIfExists('passcode', $data ?? [], null);
        $this->setIfExists('status', $data ?? [], null);
        $this->setIfExists('placeholder_name', $data ?? [], null);
    }

    public function hasActualInstance(): bool
    {
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
    }

    public function getActualInstance()
    {
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['email'] === null) {
            $invalidProperties[] = "'email' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        if (is_null($id)) {
            throw new \InvalidArgumentException('non-nullable id cannot be null');
        }
        $this->container['id'] = $id;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name name
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email email
     *
     * @return self
     */
    public function setEmail($email)
    {
        if (is_null($email)) {
            throw new \InvalidArgumentException('non-nullable email cannot be null');
        }
        $this->container['email'] = $email;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets role
     *
     * @return string|null
     */
    public function getRole()
    {
        return $this->container['role'];
    }

    /**
     * Sets role
     *
     * @param string|null $role role
     *
     * @return self
     */
    public function setRole($role)
    {
        if (is_null($role)) {
            throw new \InvalidArgumentException('non-nullable role cannot be null');
        }
        $this->container['role'] = $role;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets message
     *
     * @return string|null
     */
    public function getMessage()
    {
        return $this->container['message'];
    }

    /**
     * Sets message
     *
     * @param string|null $message message
     *
     * @return self
     */
    public function setMessage($message)
    {
        if (is_null($message)) {
            array_push($this->openAPINullablesSetToNull, 'message');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('message', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['message'] = $message;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets subject
     *
     * @return string|null
     */
    public function getSubject()
    {
        return $this->container['subject'];
    }

    /**
     * Sets subject
     *
     * @param string|null $subject subject
     *
     * @return self
     */
    public function setSubject($subject)
    {
        if (is_null($subject)) {
            array_push($this->openAPINullablesSetToNull, 'subject');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('subject', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['subject'] = $subject;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets send_email
     *
     * @return bool|null
     */
    public function getSendEmail()
    {
        return $this->container['send_email'];
    }

    /**
     * Sets send_email
     *
     * @param bool|null $send_email send_email
     *
     * @return self
     */
    public function setSendEmail($send_email)
    {
        if (is_null($send_email)) {
            array_push($this->openAPINullablesSetToNull, 'send_email');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('send_email', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['send_email'] = $send_email;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets send_email_delay
     *
     * @return int|null
     */
    public function getSendEmailDelay()
    {
        return $this->container['send_email_delay'];
    }

    /**
     * Sets send_email_delay
     *
     * @param int|null $send_email_delay send_email_delay
     *
     * @return self
     */
    public function setSendEmailDelay($send_email_delay)
    {
        if (is_null($send_email_delay)) {
            array_push($this->openAPINullablesSetToNull, 'send_email_delay');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('send_email_delay', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['send_email_delay'] = $send_email_delay;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets signing_order
     *
     * @return int|null
     */
    public function getSigningOrder()
    {
        return $this->container['signing_order'];
    }

    /**
     * Sets signing_order
     *
     * @param int|null $signing_order signing_order
     *
     * @return self
     */
    public function setSigningOrder($signing_order)
    {
        if (is_null($signing_order)) {
            throw new \InvalidArgumentException('non-nullable signing_order cannot be null');
        }
        $this->container['signing_order'] = $signing_order;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets signing_url
     *
     * @return string|null
     */
    public function getSigningUrl()
    {
        return $this->container['signing_url'];
    }

    /**
     * Sets signing_url
     *
     * @param string|null $signing_url signing_url
     *
     * @return self
     */
    public function setSigningUrl($signing_url)
    {
        if (is_null($signing_url)) {
            array_push($this->openAPINullablesSetToNull, 'signing_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('signing_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['signing_url'] = $signing_url;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets embedded_signing_url
     *
     * @return string|null
     */
    public function getEmbeddedSigningUrl()
    {
        return $this->container['embedded_signing_url'];
    }

    /**
     * Sets embedded_signing_url
     *
     * @param string|null $embedded_signing_url embedded_signing_url
     *
     * @return self
     */
    public function setEmbeddedSigningUrl($embedded_signing_url)
    {
        if (is_null($embedded_signing_url)) {
            array_push($this->openAPINullablesSetToNull, 'embedded_signing_url');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('embedded_signing_url', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['embedded_signing_url'] = $embedded_signing_url;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets bounced
     *
     * @return bool|null
     */
    public function getBounced()
    {
        return $this->container['bounced'];
    }

    /**
     * Sets bounced
     *
     * @param bool|null $bounced bounced
     *
     * @return self
     */
    public function setBounced($bounced)
    {
        if (is_null($bounced)) {
            array_push($this->openAPINullablesSetToNull, 'bounced');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bounced', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bounced'] = $bounced;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets bounced_details
     *
     * @return string|null
     */
    public function getBouncedDetails()
    {
        return $this->container['bounced_details'];
    }

    /**
     * Sets bounced_details
     *
     * @param string|null $bounced_details bounced_details
     *
     * @return self
     */
    public function setBouncedDetails($bounced_details)
    {
        if (is_null($bounced_details)) {
            array_push($this->openAPINullablesSetToNull, 'bounced_details');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('bounced_details', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['bounced_details'] = $bounced_details;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets attachment_requests
     *
     * @return \SignWell\Sdk\Models\AttachmentRequestInfo[]|null
     */
    public function getAttachmentRequests()
    {
        return $this->container['attachment_requests'];
    }

    /**
     * Sets attachment_requests
     *
     * @param \SignWell\Sdk\Models\AttachmentRequestInfo[]|null $attachment_requests attachment_requests
     *
     * @return self
     */
    public function setAttachmentRequests($attachment_requests)
    {
        if (is_null($attachment_requests)) {
            throw new \InvalidArgumentException('non-nullable attachment_requests cannot be null');
        }
        $this->container['attachment_requests'] = $attachment_requests;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets passcode
     *
     * @return string|null
     */
    public function getPasscode()
    {
        return $this->container['passcode'];
    }

    /**
     * Sets passcode
     *
     * @param string|null $passcode passcode
     *
     * @return self
     */
    public function setPasscode($passcode)
    {
        if (is_null($passcode)) {
            array_push($this->openAPINullablesSetToNull, 'passcode');
        } else {
            $nullablesSetToNull = $this->getOpenAPINullablesSetToNull();
            $index = array_search('passcode', $nullablesSetToNull);
            if ($index !== false) {
                unset($nullablesSetToNull[$index]);
                $this->setOpenAPINullablesSetToNull($nullablesSetToNull);
            }
        }
        $this->container['passcode'] = $passcode;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets status
     *
     * @return string|null
     */
    public function getStatus()
    {
        return $this->container['status'];
    }

    /**
     * Sets status
     *
     * @param string|null $status status
     *
     * @return self
     */
    public function setStatus($status)
    {
        if (is_null($status)) {
            throw new \InvalidArgumentException('non-nullable status cannot be null');
        }
        $this->container['status'] = $status;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets placeholder_name
     *
     * @return string|null
     */
    public function getPlaceholderName()
    {
        return $this->container['placeholder_name'];
    }

    /**
     * Sets placeholder_name
     *
     * @param string|null $placeholder_name placeholder_name
     *
     * @return self
     */
    public function setPlaceholderName($placeholder_name)
    {
        if (is_null($placeholder_name)) {
            throw new \InvalidArgumentException('non-nullable placeholder_name cannot be null');
        }
        $this->container['placeholder_name'] = $placeholder_name;
        $this->normalizeAfterSet();

        return $this;
    }
    private function normalizeAfterSet(): void
    {
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
