<?php

declare(strict_types=1);
/**
 * FieldsInnerInner
 *
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk\Models;

use ArrayAccess;
use SignWell\Sdk\ObjectSerializer;

/**
 * FieldsInnerInner Class Doc Comment
 *
 * @category Class
 * @package  SignWell\Sdk
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<string, mixed>
 */
class FieldsInnerInner implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Fields_inner_inner';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'x' => 'float',
        'y' => 'float',
        'page' => 'int',
        'recipient_id' => 'string',
        'type' => '\SignWell\Sdk\Models\FieldType',
        'required' => 'bool',
        'label' => 'string',
        'value' => '\SignWell\Sdk\Models\AdditionalFieldsInnerInnerValue',
        'api_id' => 'string',
        'name' => 'string',
        'validation' => '\SignWell\Sdk\Models\TextValidation',
        'fixed_width' => 'bool',
        'lock_sign_date' => 'bool',
        'date_format' => '\SignWell\Sdk\Models\DateFormat',
        'height' => 'float',
        'width' => 'float',
        'options' => '\SignWell\Sdk\Models\DropdownOption[]',
        'default_option' => 'string',
        'allow_other' => 'bool'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'x' => 'float',
        'y' => 'float',
        'page' => null,
        'recipient_id' => null,
        'type' => null,
        'required' => null,
        'label' => null,
        'value' => null,
        'api_id' => null,
        'name' => null,
        'validation' => null,
        'fixed_width' => null,
        'lock_sign_date' => null,
        'date_format' => null,
        'height' => 'float',
        'width' => 'float',
        'options' => null,
        'default_option' => null,
        'allow_other' => null
    ];

    /**
      * Array of nullable properties. Used for (de)serialization
      *
      * @var boolean[]
      */
    protected static array $openAPINullables = [
        'x' => false,
        'y' => false,
        'page' => false,
        'recipient_id' => false,
        'type' => false,
        'required' => false,
        'label' => false,
        'value' => false,
        'api_id' => false,
        'name' => false,
        'validation' => false,
        'fixed_width' => false,
        'lock_sign_date' => false,
        'date_format' => false,
        'height' => false,
        'width' => false,
        'options' => false,
        'default_option' => false,
        'allow_other' => false
    ];

    /**
      * If a nullable field gets set to null, insert it here
      *
      * @var boolean[]
      */
    protected array $openAPINullablesSetToNull = [];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of nullable properties
     *
     * @return array
     */
    protected static function openAPINullables(): array
    {
        return self::$openAPINullables;
    }

    /**
     * Array of nullable field names deliberately set to null
     *
     * @return boolean[]
     */
    private function getOpenAPINullablesSetToNull(): array
    {
        return $this->openAPINullablesSetToNull;
    }

    /**
     * Setter - Array of nullable field names deliberately set to null
     *
     * @param boolean[] $openAPINullablesSetToNull
     */
    private function setOpenAPINullablesSetToNull(array $openAPINullablesSetToNull): void
    {
        $this->openAPINullablesSetToNull = $openAPINullablesSetToNull;
    }

    /**
     * Checks if a property is nullable
     *
     * @param string $property
     * @return bool
     */
    public static function isNullable(string $property): bool
    {
        return self::openAPINullables()[$property] ?? false;
    }

    /**
     * Checks if a nullable property is set to null.
     *
     * @param string $property
     * @return bool
     */
    public function isNullableSetToNull(string $property): bool
    {
        return in_array($property, $this->getOpenAPINullablesSetToNull(), true);
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'x' => 'x',
        'y' => 'y',
        'page' => 'page',
        'recipient_id' => 'recipient_id',
        'type' => 'type',
        'required' => 'required',
        'label' => 'label',
        'value' => 'value',
        'api_id' => 'api_id',
        'name' => 'name',
        'validation' => 'validation',
        'fixed_width' => 'fixed_width',
        'lock_sign_date' => 'lock_sign_date',
        'date_format' => 'date_format',
        'height' => 'height',
        'width' => 'width',
        'options' => 'options',
        'default_option' => 'default_option',
        'allow_other' => 'allow_other'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'x' => 'setX',
        'y' => 'setY',
        'page' => 'setPage',
        'recipient_id' => 'setRecipientId',
        'type' => 'setType',
        'required' => 'setRequired',
        'label' => 'setLabel',
        'value' => 'setValue',
        'api_id' => 'setApiId',
        'name' => 'setName',
        'validation' => 'setValidation',
        'fixed_width' => 'setFixedWidth',
        'lock_sign_date' => 'setLockSignDate',
        'date_format' => 'setDateFormat',
        'height' => 'setHeight',
        'width' => 'setWidth',
        'options' => 'setOptions',
        'default_option' => 'setDefaultOption',
        'allow_other' => 'setAllowOther'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'x' => 'getX',
        'y' => 'getY',
        'page' => 'getPage',
        'recipient_id' => 'getRecipientId',
        'type' => 'getType',
        'required' => 'getRequired',
        'label' => 'getLabel',
        'value' => 'getValue',
        'api_id' => 'getApiId',
        'name' => 'getName',
        'validation' => 'getValidation',
        'fixed_width' => 'getFixedWidth',
        'lock_sign_date' => 'getLockSignDate',
        'date_format' => 'getDateFormat',
        'height' => 'getHeight',
        'width' => 'getWidth',
        'options' => 'getOptions',
        'default_option' => 'getDefaultOption',
        'allow_other' => 'getAllowOther'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];


    /**
     * Constructor
     *
     * @param mixed[]|null $data Associated array of property values
     *                      initializing the model
     */
    public function __construct($data = null)
    {
        $this->setIfExists('x', $data ?? [], null);
        $this->setIfExists('y', $data ?? [], null);
        $this->setIfExists('page', $data ?? [], null);
        $this->setIfExists('recipient_id', $data ?? [], null);
        $this->setIfExists('type', $data ?? [], null);
        $this->setIfExists('required', $data ?? [], true);
        $this->setIfExists('label', $data ?? [], null);
        $this->setIfExists('value', $data ?? [], null);
        $this->setIfExists('api_id', $data ?? [], null);
        $this->setIfExists('name', $data ?? [], null);
        $this->setIfExists('validation', $data ?? [], null);
        $this->setIfExists('fixed_width', $data ?? [], false);
        $this->setIfExists('lock_sign_date', $data ?? [], false);
        $this->setIfExists('date_format', $data ?? [], null);
        $this->setIfExists('height', $data ?? [], null);
        $this->setIfExists('width', $data ?? [], null);
        $this->setIfExists('options', $data ?? [], null);
        $this->setIfExists('default_option', $data ?? [], null);
        $this->setIfExists('allow_other', $data ?? [], false);
        $this->normalizeCheckboxValue();
    }

    public function hasActualInstance(): bool
    {
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
        return false;
    }

    public function getActualInstance()
    {
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
        return null;
    }

    /**
    * Sets $this->container[$variableName] to the given data or to the given default Value; if $variableName
    * is nullable and its value is set to null in the $fields array, then mark it as "set to null" in the
    * $this->openAPINullablesSetToNull array
    *
    * @param string $variableName
    * @param array  $fields
    * @param mixed  $defaultValue
    */
    private function setIfExists(string $variableName, array $fields, $defaultValue): void
    {
        if (self::isNullable($variableName) && array_key_exists($variableName, $fields) && is_null($fields[$variableName])) {
            $this->openAPINullablesSetToNull[] = $variableName;
        }

        $this->container[$variableName] = $fields[$variableName] ?? $defaultValue;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['x'] === null) {
            $invalidProperties[] = "'x' can't be null";
        }
        if ($this->container['y'] === null) {
            $invalidProperties[] = "'y' can't be null";
        }
        if ($this->container['page'] === null) {
            $invalidProperties[] = "'page' can't be null";
        }
        if ($this->container['recipient_id'] === null) {
            $invalidProperties[] = "'recipient_id' can't be null";
        }
        if ($this->container['type'] === null) {
            $invalidProperties[] = "'type' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets x
     *
     * @return float
     */
    public function getX()
    {
        return $this->container['x'];
    }

    /**
     * Sets x
     *
     * @param float $x Horizontal value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
     *
     * @return self
     */
    public function setX($x)
    {
        if (is_null($x)) {
            throw new \InvalidArgumentException('non-nullable x cannot be null');
        }
        $this->container['x'] = $x;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets y
     *
     * @return float
     */
    public function getY()
    {
        return $this->container['y'];
    }

    /**
     * Sets y
     *
     * @param float $y Vertical value in the coordinates of the field (in pixels). Coordinates are specific to the page where fields are located.
     *
     * @return self
     */
    public function setY($y)
    {
        if (is_null($y)) {
            throw new \InvalidArgumentException('non-nullable y cannot be null');
        }
        $this->container['y'] = $y;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets page
     *
     * @return int
     */
    public function getPage()
    {
        return $this->container['page'];
    }

    /**
     * Sets page
     *
     * @param int $page The page number within the file. If the page does not exist within the file then the field won't be created.
     *
     * @return self
     */
    public function setPage($page)
    {
        if (is_null($page)) {
            throw new \InvalidArgumentException('non-nullable page cannot be null');
        }
        $this->container['page'] = $page;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets recipient_id
     *
     * @return string
     */
    public function getRecipientId()
    {
        return $this->container['recipient_id'];
    }

    /**
     * Sets recipient_id
     *
     * @param string $recipient_id Unique identifier of the recipient assigned to the field. Recipients assigned to fields will be the only ones that will see and be able to complete those fields.
     *
     * @return self
     */
    public function setRecipientId($recipient_id)
    {
        if (is_null($recipient_id)) {
            throw new \InvalidArgumentException('non-nullable recipient_id cannot be null');
        }
        $this->container['recipient_id'] = $recipient_id;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets type
     *
     * @return \SignWell\Sdk\Models\FieldType
     */
    public function getType()
    {
        return $this->container['type'];
    }

    /**
     * Sets type
     *
     * @param \SignWell\Sdk\Models\FieldType $type type
     *
     * @return self
     */
    public function setType($type)
    {
        if (is_null($type)) {
            throw new \InvalidArgumentException('non-nullable type cannot be null');
        }
        $this->container['type'] = $type;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets required
     *
     * @return bool|null
     */
    public function getRequired()
    {
        return $this->container['required'];
    }

    /**
     * Sets required
     *
     * @param bool|null $required Whether the field must be completed by the recipient. Defaults to `true` except for checkbox type fields.
     *
     * @return self
     */
    public function setRequired($required)
    {
        if (is_null($required)) {
            throw new \InvalidArgumentException('non-nullable required cannot be null');
        }
        $this->container['required'] = $required;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets label
     *
     * @return string|null
     */
    public function getLabel()
    {
        return $this->container['label'];
    }

    /**
     * Sets label
     *
     * @param string|null $label Text and Date fields only: label that is displayed when the field is empty.
     *
     * @return self
     */
    public function setLabel($label)
    {
        if (is_null($label)) {
            throw new \InvalidArgumentException('non-nullable label cannot be null');
        }
        $this->container['label'] = $label;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets value
     *
     * @return \SignWell\Sdk\Models\AdditionalFieldsInnerInnerValue|null
     */
    public function getValue()
    {
        return $this->container['value'];
    }

    /**
     * Sets value
     *
     * @param \SignWell\Sdk\Models\AdditionalFieldsInnerInnerValue|null $value value
     *
     * @return self
     */
    public function setValue($value)
    {
        if (is_null($value)) {
            throw new \InvalidArgumentException('non-nullable value cannot be null');
        }
        $this->container['value'] = $value;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets api_id
     *
     * @return string|null
     */
    public function getApiId()
    {
        return $this->container['api_id'];
    }

    /**
     * Sets api_id
     *
     * @param string|null $api_id Unique identifier of the field. Useful when needing to reference specific field values or update a document and its fields.
     *
     * @return self
     */
    public function setApiId($api_id)
    {
        if (is_null($api_id)) {
            throw new \InvalidArgumentException('non-nullable api_id cannot be null');
        }
        $this->container['api_id'] = $api_id;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets name
     *
     * @return string|null
     */
    public function getName()
    {
        return $this->container['name'];
    }

    /**
     * Sets name
     *
     * @param string|null $name Checkbox fields only. At least 2 checkbox fields in an array of fields must be assigned to the same recipient and grouped with selection requirements.
     *
     * @return self
     */
    public function setName($name)
    {
        if (is_null($name)) {
            throw new \InvalidArgumentException('non-nullable name cannot be null');
        }
        $this->container['name'] = $name;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets validation
     *
     * @return \SignWell\Sdk\Models\TextValidation|null
     */
    public function getValidation()
    {
        return $this->container['validation'];
    }

    /**
     * Sets validation
     *
     * @param \SignWell\Sdk\Models\TextValidation|null $validation validation
     *
     * @return self
     */
    public function setValidation($validation)
    {
        if (is_null($validation)) {
            throw new \InvalidArgumentException('non-nullable validation cannot be null');
        }
        $this->container['validation'] = $validation;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets fixed_width
     *
     * @return bool|null
     */
    public function getFixedWidth()
    {
        return $this->container['fixed_width'];
    }

    /**
     * Sets fixed_width
     *
     * @param bool|null $fixed_width Text fields only: whether the field width will stay fixed and text will display in multiple lines, rather than one long line. If set to `false` the field width will automatically grow horizontally to fit text on one line. Defaults to `false`.
     *
     * @return self
     */
    public function setFixedWidth($fixed_width)
    {
        if (is_null($fixed_width)) {
            throw new \InvalidArgumentException('non-nullable fixed_width cannot be null');
        }
        $this->container['fixed_width'] = $fixed_width;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets lock_sign_date
     *
     * @return bool|null
     */
    public function getLockSignDate()
    {
        return $this->container['lock_sign_date'];
    }

    /**
     * Sets lock_sign_date
     *
     * @param bool|null $lock_sign_date Date fields only: makes fields readonly and automatically populates with the date the recipient signed. Defaults to `false`.
     *
     * @return self
     */
    public function setLockSignDate($lock_sign_date)
    {
        if (is_null($lock_sign_date)) {
            throw new \InvalidArgumentException('non-nullable lock_sign_date cannot be null');
        }
        $this->container['lock_sign_date'] = $lock_sign_date;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets date_format
     *
     * @return \SignWell\Sdk\Models\DateFormat|null
     */
    public function getDateFormat()
    {
        return $this->container['date_format'];
    }

    /**
     * Sets date_format
     *
     * @param \SignWell\Sdk\Models\DateFormat|null $date_format date_format
     *
     * @return self
     */
    public function setDateFormat($date_format)
    {
        if (is_null($date_format)) {
            throw new \InvalidArgumentException('non-nullable date_format cannot be null');
        }
        $this->container['date_format'] = $date_format;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets height
     *
     * @return float|null
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param float|null $height Height of the field (in pixels). Maximum height varies by field type: Signature/Initials (200px), others (74px). When using text tags if the height is greater than the maximum height, the height will be set to the maximum height.
     *
     * @return self
     */
    public function setHeight($height)
    {
        if (is_null($height)) {
            throw new \InvalidArgumentException('non-nullable height cannot be null');
        }
        $this->container['height'] = $height;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets width
     *
     * @return float|null
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param float|null $width Width of the field (in pixels). For text fields, width will auto-grow unless `fixed_width` is true.
     *
     * @return self
     */
    public function setWidth($width)
    {
        if (is_null($width)) {
            throw new \InvalidArgumentException('non-nullable width cannot be null');
        }
        $this->container['width'] = $width;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets options
     *
     * @return \SignWell\Sdk\Models\DropdownOption[]|null
     */
    public function getOptions()
    {
        return $this->container['options'];
    }

    /**
     * Sets options
     *
     * @param \SignWell\Sdk\Models\DropdownOption[]|null $options Array of dropdown options (for dropdown/select fields only)
     *
     * @return self
     */
    public function setOptions($options)
    {
        if (is_null($options)) {
            throw new \InvalidArgumentException('non-nullable options cannot be null');
        }
        $this->container['options'] = $options;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets default_option
     *
     * @return string|null
     */
    public function getDefaultOption()
    {
        return $this->container['default_option'];
    }

    /**
     * Sets default_option
     *
     * @param string|null $default_option Default selected option (for dropdown/select fields only)
     *
     * @return self
     */
    public function setDefaultOption($default_option)
    {
        if (is_null($default_option)) {
            throw new \InvalidArgumentException('non-nullable default_option cannot be null');
        }
        $this->container['default_option'] = $default_option;
        $this->normalizeAfterSet();

        return $this;
    }

    /**
     * Gets allow_other
     *
     * @return bool|null
     */
    public function getAllowOther()
    {
        return $this->container['allow_other'];
    }

    /**
     * Sets allow_other
     *
     * @param bool|null $allow_other Whether to allow \"Other\" option with text input (for dropdown/select fields only)
     *
     * @return self
     */
    public function setAllowOther($allow_other)
    {
        if (is_null($allow_other)) {
            throw new \InvalidArgumentException('non-nullable allow_other cannot be null');
        }
        $this->container['allow_other'] = $allow_other;
        $this->normalizeAfterSet();

        return $this;
    }
    private function normalizeAfterSet(): void
    {
        $this->normalizeCheckboxValue();
    }

    private function normalizeCheckboxValue(): void
    {
        if (($this->container['type'] ?? null) !== 'checkbox' || !array_key_exists('value', $this->container) || $this->container['value'] === null) {
            return;
        }

        $this->container['value'] = self::normalizeCheckboxScalar($this->container['value']);
    }

    private static function normalizeCheckboxScalar($value): string
    {
        if (is_object($value) && method_exists($value, 'hasActualInstance') && $value->hasActualInstance()) {
            $value = $value->getActualInstance();
        }

        if (is_bool($value)) {
            return $value ? 't' : 'f';
        }

        if (is_string($value)) {
            $normalized = strtolower(trim($value));
            if ($normalized === 'true' || $normalized === 't') {
                return 't';
            }
            if ($normalized === 'false' || $normalized === 'f') {
                return 'f';
            }
        }

        throw new \InvalidArgumentException('Checkbox field values must be boolean or one of "true", "false", "t", or "f".');
    }

    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset): bool
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value): void
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset): void
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    #[\ReturnTypeWillChange]
    public function jsonSerialize()
    {
        return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
