<?php

declare(strict_types=1);
/**
 * ApiException
 * PHP version 8.2
 *
 * @category Class
 * @package  SignWell\Sdk
 */

/**
 * SignWell Developer API
 *
 * API for creating, managing, and tracking electronic signature workflows.
 *
 * The version of the OpenAPI document: v1
 * Contact: support@signwell.com
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.12.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace SignWell\Sdk;

/**
 * Base SDK exception retained for OpenAPI Generator compatibility.
 */
class ApiException extends Errors\ApiError
{
    /**
     * The HTTP body of the server response either as JSON or string.
     *
     * @var \stdClass|string|null
     */
    protected $responseBody;

    /**
     * The HTTP headers of the server response.
     *
     * @var string[][]|null
     */
    protected $responseHeaders;

    /**
     * The deserialized response object.
     *
     * @var mixed
     */
    protected $responseObject;

    /**
     * @param string $message
     * @param int $code
     * @param string[][]|null $responseHeaders
     * @param \stdClass|string|null $responseBody
     */
    public function __construct($message = '', $code = 0, $responseHeaders = [], $responseBody = null, ?\Throwable $previous = null)
    {
        parent::__construct($message, (int) $code, $previous);
        $this->responseHeaders = $responseHeaders;
        $this->responseBody = $responseBody;
    }

    /**
     * @param string[][]|null $responseHeaders
     * @param \stdClass|string|null $responseBody
     */
    public static function fromResponse(
        string $message,
        int $code = 0,
        ?array $responseHeaders = null,
        $responseBody = null,
        ?\Throwable $previous = null
    ): self {
        $class = match ($code) {
            400 => Errors\BadRequestError::class,
            401 => Errors\AuthenticationError::class,
            403 => Errors\ForbiddenError::class,
            404 => Errors\NotFoundError::class,
            409 => Errors\ConflictError::class,
            422 => Errors\UnprocessableEntityError::class,
            429 => Errors\RateLimitError::class,
            500, 502, 503, 504 => Errors\InternalServerError::class,
            default => self::class,
        };

        return new $class($message, $code, $responseHeaders, $responseBody, $previous);
    }

    /**
     * Gets the HTTP response headers.
     *
     * @return string[][]|null
     */
    public function getResponseHeaders()
    {
        return $this->responseHeaders;
    }

    /**
     * Gets the HTTP body of the server response either as JSON or string.
     *
     * @return \stdClass|string|null
     */
    public function getResponseBody()
    {
        return $this->responseBody;
    }

    /**
     * @param mixed $obj Deserialized response object
     */
    public function setResponseObject($obj): void
    {
        $this->responseObject = $obj;
    }

    /**
     * @return mixed
     */
    public function getResponseObject()
    {
        return $this->responseObject;
    }
}
